data = [
    ('Arkadaşlarımın sürpriz doğum günü partisiyle adeta şaşkına döndüm.', 'şaşkın'),
    ('Annemi çok seviyorum', 'sevgi dolu'),
    ('Yarın yapmam gereken sunum için kaygılıyım, acaba başarılı olabilecek miyim?', 'kaygılı'),
    ('Deniz kenarında oturup gün batımını izlemek insana huzur veriyor.', 'huzurlu'),
    ('Yeni işimdeki adaletsizlik beni sinirlendiriyor.', 'öfkeli'),
    ('Karşılaştığımız durum, nötr bir tepkiyle karşılandı.', 'nötr'),
    ('Tiksinmiş bir şekilde o yemeği yedim.', 'tiksinmiş'),
    ('Bu kitabı sonunda bitirebildim.', 'mutlu'),
    ('Arkadaşlarımla yaşadığım bir anıyı hatırlayınca duygusal bir karışıklık hissettim.', 'duygu durumu karışık'),
    ('Sevdiğim biri bugün vefat etti.', 'üzgün'),
    ('Gece karanlığında yürürken garip sesler duyarak korkmuş hissettim.', 'korkmuş'),
    ('Yarınki tatil planı için çok heyecanlıyım!', 'heyecanlı'),
    ('Babamı çok seviyorum', 'sevgi dolu'),
    ('Maalesef sınavımdan beklediğimden daha düşük bir not aldım.', 'üzgün'),
    ('Dışarıda hükümet konusu açıldığında görüşümü belirtmeyerek tarafsız bir tutum sergiliyorum.', 'nötr'),
    ('Geleceğimle ilgili belirsizliklerden dolayı oldukça endişeliyim.', 'kaygılı'),
    ('Yarınki tatil planı için çok heyecanlıyım, harika bir gün geçireceğim!', 'duygu durumu karışık'),
    ('Harika bir gün beni bekliyor.', 'mutlu'),
    ('İzlediğim korku filmi yüzünden yatağa girdiğimde etrafımdaki karanlık beni çok korkuttu.', 'korkmuş'),
    ('Bugün yeni bir işe başladığım için içim kıpır kıpır.', 'heyecanlı'),
    ('Arkadaşımın sıktığı şekerli parfüm çok iğrenç kokuyor.', 'tiksinmiş'),
    ('Kedimin babama olan bağlılığı beni hayrete düşürdü.', 'şaşkın'),
    ('Annemin abime sergilediği tutumdan dolayı kıskançlıktan çılgına döndüm.', 'öfkeli'),
    ('Doğada yürüyüş yapmak gibisi yok.', 'huzurlu'),
    ('En yakınlarımı giderek kaybediyorum.', 'üzgün'),
    ('Kedimi her gördüğümde yeniden aşık oluyorum.', 'sevgi dolu'),
    ('Verdiğim emeklerin karşılığını aldım ve sınavı kazandım.', 'mutlu'),
    ('Bana veya başkalarına yapılan haksızlıklar beni çok sinirlendiriyor.', 'öfkeli'),
    ('Doktorların öldüğünü söylediği hasta, hayata döndü. Bu bir mucize.', 'şaşkın'),
    ('Ondan beklemediğim bu hareket karşısında ne hissedeceğimi bilemedim.', 'duygu durumu karışık'),
    ('Gelen bomba ihbarı hepimizi çok korkuttu.', 'korkmuş'),
    ('O çöp tenekesinin kapağını açtığımda midem bulandı, hemen kapağı kapatıp oradan uzaklaştım.', 'tiksinmiş'),
    ('Antreman sonrası yaptığım sıcak duş, beni çok rahatlatıyor.', 'huzurlu'),
    ('İlk kez uçağa bineceğim için çok heyecanlıyım.', 'heyecanlı'),
    ('Merhaba! Bugün nasılsınız?', 'nötr'),
    ('İş görüşmelerine gitmek beni çok geriyor.', 'kaygılı'),
    ('Her ne kadar halsiz ve yorgun olsam da konu gezmek olunca hiçbir şeyim yokmuş gibi mutlu mesut etrafta geziyorum.', 'duygu durumu karışık'),
    ('Bana her sarıldığında annemin yüzünde oluşan o sevgi dolu gülümseme, bana her şeyin üstesinden gelebileceğimi hatırlatıyor.', 'sevgi dolu'),
    ('Çevremdekilerin beni anlamaması yüzünden sürekli ağlıyorum.', 'üzgün'),
    ('Denizde yüzerken huzurla içimi dolduran bir sessizlik, beni kendi dünyama çekti. Doğanın güzelliğini seyrederken kendimi derin suların akışına bıraktım.', 'huzurlu'),
    ('Toplantıda yaşanan o derin sessizlik, beni çok gerdi.', 'kaygılı'),
    ('Onu her gördüğümde kalbim yerinden çıkacak gibi oluyor.', 'heyecanlı'),
    ('Bir çocuğun yüzündeki o masum mutluluk, oynadığı oyuncaklarla doldurduğu oyun odasında saklıydı. Her bir kahkahası, odanın içine neşyle dolduruyor.', 'mutlu'),
    ('Bir mucizeye tanık olurken, şaşkınlıkla gözlerini ovuşturuyor ve inanılması güç bir gerçeklikle karşı karşıya olduğunu düşünüyorsun.', 'şaşkın'),
    ('Dengeli bir ruh haliyle, olaylara tarafsız bir şekilde bakabiliyor ve duygusal tepkilerden uzak bir perspektifle düşünebiliyorsun.', 'nötr'),
    ('Beklenmedik bir tehlike karşısında, içinde bir korku dalgası yükseliyor ve içsel sıkıntılarla mücadele etmek zorunda kalıyorsun.', 'korkmuş'),
    ('Arkadaşımın bu davranışları karşısında çok rahatsız oldum. Ancak içimdeki bu tiksinme duygusuyla baş etmeye çalıştım.', 'tiksinmiş'),
    ('Gördüğüm haksızlık karşısında içimde bir öfke yükseliyor, sanki içimde bir volkan patlamaya hazır gibi. Adaletsizliğe, hukusuzluğa ve haksızlığa karşı içimdeki ateşle mücadele etmek gerçekten zorlayıcı olabiliyor.', 'öfkeli'),
    ('Bir vedanın ardından hissedilen derin üzüntü, gözlerde beliren yaşlarla birlikte yüreği sarıyordu. O anki hüzün, anıların ve geçmişin iç içe geçtiği bir duygusal yoğunluktu.', 'üzgün'),
    ('Bir şelalenin yanında oturduğumda, suyun akışını izlemek huzur dolu bir deneyim oluyor. Sanki zaman duruyor, her şeyin yerli yerinde olduğunu hissediyorum ve içsel bir dinginlik sarıyor ruhumu.', 'huzurlu'),
    ('Bir karar vermem gerektiğinde, içimdeki farklı duygular birbirleriyle yarışıyor. Bir yandan üzgünüm, bir yandan endişeliyim ve biraz da korkmuş hissediyorum. Karar vermek gerçekten zor olabiliyor.', 'duygu durumu karışık'),
    ('Elinden tuttuğunda, kalbin hızla çarpmaya başlıyor ve içindeki coşkuyla birlikte adeta havalanıyorsun.', 'heyecanlı'),
    ('Yüzümde beliren geniş bir gülümsemeyle, etrafımdaki her şey daha da parlak, daha da renkli görünüyor. İçimdeki sevinç, her bir adımımı dans eder gibi hafifletiyor ve dünya bana kutlu bir yer gibi geliyor.', 'mutlu'),
    ('Hayvanlara şefkatle yaklaştığında, içindeki sevgi dolu yaklaşımın onun da sana olan sevgisini arttırdığını hissediyorsun.', 'sevgi dolu'),
    ('Bir sırrı öğrendiğinde, şaşkınlıkla karışık bir duygu yaşıyor ve o gerçeği sindirmeye çalışıyorsun, sanki yeni bir dünyaya adım atmış gibi oluyorsun.', 'şaşkın'),
    ('Bazen etrafında gelişen olaylar karşısında, duygusal bir reaksiyon göstermeden sadece gözlemci konumunda kalmalısın.', 'nötr'),
    ('Dışarıdan gelen gürültüyle irkildim.', 'korkmuş'),
    ('Yemeği tattığım an içinde sevmediğim bir şey olduğunu anladım ve midem bulandı.', 'tiksinmiş'),
    ('Gelecek planlarını yaparken, belirsizliklerin yarattığı ihtimaller beni endişelendiriyor.', 'kaygılı'),
    ('Arkadaşımın bana ve aileme karşı yaptığı bu saygısızlık hem beni incitti hem de kızdırdı.', 'öfkeli'),
    ('Birinin yardımına ihtiyaç duyulduğunda hissedilen çaresizlik, yardım edememenin getirdiği acizlikle doluydu. O anki çaresizlik, birinin zor anında destek olamamanın yarattığı içsel bir boşluğu ifade ediyordu.', 'üzgün'),
    ('Bir sürprizle karşılaştığında, içindeki heyecanı gizlemeye çalışarak yüzünde beliren geniş bir gülümsemeyle o anın tadını çıkarıyorsun.', 'heyecanlı'),
    ('Yarınki sunum için duyduğum kaygı giderek artıyor, beklentileri karşılayabilecek miyim?', 'kaygılı'),
    ('Hayatın beklenmedik sürprizleri karşısında şaşkına döndüm.', 'şaşkın'),
    ('Karşılaştığımız durumlar bazen negatif bazen pozitif bir tepki yaratabilir, herkes farklı şeylere farklı tepkiler gösterebilir.', 'duygu durumu karışık'),
    ('Yeni yerler görmek beni mutlu ediyor.', 'mutlu'),
    ('Ona her baktığımda yeniden aşık oluyorum.', 'sevgi dolu'),
    ('İçinde bulunduğumuz durum karşısında tarafsız kalmak, bazen en sağlıklı seçenek olabilir.', 'nötr'),
    ('Son zamanlarda birden aklıma bu hayatta yalnız yaşayıp yalnız öleceğim düşüncesi geliyor ve bu düşünce beni korkutuyor.', 'korkmuş'),
    ('Bir kitabı okurken çayımı yudumlayıp yağmuru camdan izlemek, içimi huzurla dolduruyor.', 'huzurlu'),
    ('Annemle iş yaparken o işi onun istediği gibi yapmadığımda bana hep bağırıyor.', 'öfkeli'),
    ('Herkes, körü körüne emrine girdiği bu adama tiksinerek bakıyor.', 'tiksinmiş'),
    ('Aldığım haber karşısında sevinçten haykırdım.', 'mutlu'),
    ('Yeni bir spor dalı denemek istedim, ancak ya beceremezsem düşüncesi yüzünden cesaret edemedim..', 'kaygılı'),
    ('Arkadaşımın dediğine göre sevgilim evlenme teklifi edecekmiş. Heyecandan elim ayağıma dolaştı.', 'heyecanlı'),
    ('Beni orada sıcak bir yuva, huzurlu konuklar, mutlu bir kadın bekliyor.', 'huzurlu'),
    ('Düşünceleri dağılmış, karışmış, ne yapacağını bilemez duruma gelmiş.', 'şaşkın'),
    ('Birinden yana olmayan veya bir düşünceye, bir isteğe katılmayan, onu desteklemeyen, yan tutmayan; yansız, bitaraf, nötr biri o.', 'nötr'),
    ('Tuhaf şey! Hakikaten karışık bir kadın.', 'duygu durumu karışık'),
    ('O etrafta sürekli mahzun bir halde gezer..', 'üzgün'),
    ('Gerçek veya beklenen bir tehlike ile yoğun bir korku hissediyorum.', 'korkmuş'),
    ('Bu meydan okuyan öfkeli bekleyiş karşısında sustum.', 'öfkeli'),
    ('Bu ev niçin ona, tiksinç kuytularda düzensiz solumalar çağrıştırır?', 'tiksinmiş'),
    ('İlk kez denediğim oyun beni heyecanlandırdı.', 'heyecanlı'),
    ('Mutlu oldum.', 'mutlu'),
    ('Yanlış anlaşılmak can sıkıcı olabilir.', 'üzgün'),
    ('Aşkım beni sevgi dolu kucaklarla sardı.', 'sevgi dolu'),
    ('Ne oldu, iyi misin?', 'kaygılı'),
    ('Durum karışık, hem sevinçli hem de endişeli hissediyorum.', 'duygu durumu karışık'),
    ('Ondan nefret ediyorum.', 'öfkeli'),
    ('Beklenmedik haberler şaşırtıcı olabilir.', 'şaşkın'),
    ('Karanlık ve sessiz yerler korkutucu olabilir.', 'korkmuş'),
    ('Duygularımı ifade etmekte genellikle dengeliyimdir.', 'nötr'),
    ('Ona bakmak, dokunmak, kokusunu hissetmek çok rahatlatıcı.', 'huzurlu'),
    ('Sigara içen insanlardan iğreniyorum.', 'tiksinmiş'),
    ('Yaşlı amca otobüse binerken az kalsı düşüyordu. Onun için çok endişelendim.', 'kaygılı'),
    ('Genellikle nötr bir ruh halindeyim.', 'nötr'),
    ('Yakın arkadaşımın başarısı beni içtenlikle mutlu etti, onun başarısını görmek gurur duygusuyla dolmama sebep oldu.', 'mutlu'),
    ('Hediyesini açmak için sabırsızlanıyordu.', 'heyecanlı'),
    ('Birinin yardımına ihtiyaç duyduğumu hissetmek, hem yardım alma isteğiyle hem de gurur kırıklığıyla içimi doldurdu.', 'duygu durumu karışık'),
    ('Bana aşk dolu gözlerle baktığında içim kıpır kıpır oluyor.', 'sevgi dolu'),
    ('Uyumadan önce klasik müzik dinlemek, güzel bir uyku çekmemi sağlıyor.', 'huzurlu'),
    ('Arkadaşıın bana yaptığı şaka karşısında nutkum tutuldu.', 'şaşkın'),
    ('Şimdilerde zor zamanlardan geçiyorum. Çünkü yapmadığım bir şey için suçlandım.', 'üzgün'),
    ('Babam arkama aniden yaklaşınca yerimden zıpladım.', 'korkmuş'),
    ('Küçümsenmekten nefret ediyorum.', 'öfkeli'),
    ('Kan gibi uyarıcılar görmek veya koklamak bazı insanlarda tiksinme duygusu yaratabilir. ', 'tiksinmiş'),
    ('Geçen hafta sonu, köpeğim kaybolduğunda içimde büyük bir endişe oluştu. Onu bulana kadar sürekli kaygılıydım.', 'kaygılı'),
    ('Yoğun bir günün ardından, hiçbir duygusal tepki vermeden sadece sessizce odamda oturmak istedim. Genellikle nötr bir ruh halindeydim ve herhangi bir duyguyu dışa vurmaktan kaçınıyordum.', 'nötr'),
    ('En yakın arkadaşımın başarılı bir proje sonucunda ödül kazanması beni içtenlikle mutlu etti. Onun başarısı, gurur duygusuyla dolmama sebep oldu.', 'mutlu'),
    ('Yakın bir arkadaşımın doğum günü için aldığı hediyeyi açmak için sabırsızlanıyordu, heyecanı yüzünden okunuyordu.', 'heyecanlı'),
    ('Birinin yardımına ihtiyaç duyduğumu hissetmek, hem yardım alma isteğiyle hem de gurur kırıklığıyla içimi doldurdu.', 'duygu durumu karışık'),
    ('Sevdiğim insan bana aşk dolu gözlerle baktığında, içim kıpır kıpır oluyor.', 'sevgi dolu'),
    ('Ağaçların gölgeleri altında uzanmak ve sessiz bir göl kenarında kitap okumak, benim için huzurlu bir an yaratır. Doğanın sessizliği ve hafif rüzgarın esintisi, içimi huzurla doldurur.', 'huzurlu'),
    ('Arkadaşımın yaptığı şaka karşısında şaşkına döndüm, adeta nutkum tutuldu.', 'şaşkın'),
    ('Son zamanlarda zor bir dönemden geçiyorum. Yapmadığım bir şey için suçlandığım için oldukça üzgünüm..', 'üzgün'),
    ('Gece yarısı ani bir gürültüyle uyandığımda, kalbim hızla atmaya başladı ve etrafıma bakarken korkmuş bir şekilde titremeye başladım. O an, içimde belirsiz bir tehlikenin varlığıyla dolu bir korku hissettim.', 'korkmuş'),
    ('Her ne kadar acelem olsada trafik yüzünden geç kaldım ve bu yüzden bir güzel fırça yedim.', 'öfkeli'),
    ('İnsanların öksürmelerinden sonra o elleriyle otobüsün direklerini tutmaları çok iğrneç.', 'tiksinmiş'),
    ('Bir şeyi kaybettiğimde, içimde tarifsiz bir hüzün oluşuyor. Kaybetme duygusu içimi karartıyor.', 'üzgün'),
    ('Gece geç saatlerde yalnız kaldığımda içimde bir korku oluşuyor. Korku, etrafın sessizliğiyle birleşince daha da belirginleşiyor.', 'korkmuş'),
    ('Birisi bana yapıcı eleştirilerde bulunduğunda, hem minnettarlık hem de utanç hissediyorum. Öğrenmek için minnet duyarken kusurlarımı fark etmek utanç verici.', 'duygu durumu karışık'),
    ('Sıkıcı bir günün ardından güzel bir film izlemek, ruhumu pozitif bir enerjiyle doldurdu ve içimi mutluluk kapladı.', 'mutlu'),
    ('Sinirden küplere bindim.', 'öfkeli'),
    ("Evcil hayvanımın beni karşılamasıyla içim sevgi dolu oldu, onun sevgisini hissetmek harikaydı.", "sevgi dolu"),
    ("Heyecanlı bir günün ardından sessiz bir akşamda kitap okumak, içimi huzurla dolduruyor.", "huzurlu"),
    ("Beklenmedik bir haberle şaşkına döndüm, haber öyle şaşırtıcıydı ki cevap veremedim.", "şaşkın"),
    ("Yeni bir şey öğrenme isteğiyle dolup taşarken, içimde büyük bir heyecan oluşuyor.", "heyecanlı"),
    ("Bugün sakin ve dengeli bir gün geçirdim, içim oldukça nötrdü.", "nötr"),
    ("Gelecek planları hakkında belirsizlik hissetmek, içimde bir kaygı oluşturdu.", "kaygılı"),
    ("Belirli bir görüntü karşısında içimde bir tiksinme duygusu belirdi.", "tiksinmiş"),
    ("Sevgilimle yıldönümümüzde romantik bir akşam geçirdik. Onun gülümsemesiyle içim sevgi dolu oldu.", "sevgi dolu"),
    ("Birlikte ailece yapılan tatilde, içim mutlulukla doldu. Hep beraber geçirilen vakit bizi çok mutlu etti.", "mutlu"),
    ("Yaklaşan tatil planımızı konuşurken, içimizde büyük bir heyecan oluştu. Yeni yerler görmek çok heyecan verici.", "heyecanlı"),
    ("Doğanın ortasında sessiz bir piknik yapmak, içimi huzurla dolduruyor. Kuş sesleri ve rüzgarın melodisi sakinleştirici.", "huzurlu"),
    ("Beklenmedik bir anda karşıma çıkan eski bir arkadaşım, beni şaşkına çevirdi. O anki şaşkınlığımı gizleyemedim.", "şaşkın"),
    ("Bazı günler, içimde belirgin bir duygu olmadan geçer. Genellikle nötr bir ruh halinde olmak bazen iyidir.", "nötr"),
    ("Birisi için sevinirken, aynı zamanda onun başarısızlığından dolayı da üzüldüm. İçimde çelişkili duygular belirdi.", "duygu durumu karışık"),
    ("Sevdiğim birinin ani kaybı, içimi büyük bir üzüntüyle doldurdu. Onun eksikliği hissedilir derecede acı verici.", "üzgün"),
    ("Gece yürüyüşü yaparken beklenmedik bir ses duydum, içimde bir korku hissi oluştu. Ani tehlike belirtileri insanı ürkütüyor.", "korkmuş"),
    ("Haksızlığa uğradığımı düşündüğüm bir durumda, içimde büyük bir öfke oluştu. Adaletsizlik insanı öfkelendirebilir.", "öfkeli"),
    ("Gece yarısı ani bir gürültüyle uyandığımda, kalbim hızla atmaya başladı ve etrafıma bakarken korkmuş bir şekilde titremeye başladım. O an, içimde belirsiz bir tehlikenin varlığıyla dolu bir korku hissettim.", "kaygılı"),
    ("İnsanların öksürmelerinden sonra o elleriyle otobüsün direklerini tutmaları çok iğrenç.", "tiksinmiş"),
    ('Bir başarıya ulaşmak beni sevinçten havalara uçurdu, ancak bu sevinç beraberinde bir endişe de getirdi.', 'duygu durumu karışık'),
    ('Uzun bir bekleyişin ardından alınan olumsuz bir sonuç, hem hayal kırıklığına hem de öfkeye neden oldu.', 'duygu durumu karışık'),
    ('Bir planın beklenmedik şekilde ters gitmesi, hem şaşkınlık yarattı hem de içimi huzursuz etti.', 'duygu durumu karışık'),
    ('Beklenmedik bir sürpriz karşısında duyduğum heyecan, bir yandan mutluluk verirken bir yandan da içimi hafif bir endişe kapladı.', 'duygu durumu karışık'),
    ('Belirsiz bir durumla karşılaşmak, hem korkuyla doldurdu hem de içimde belirsiz bir umut oluşturdu.', 'duygu durumu karışık'),
    ('Birinin yardımına ihtiyaç duyduğumu hissetmek, hem yardım alma isteğiyle hem de gurur kırıklığıyla içimi doldurdu.', 'duygu durumu karışık'),
    ('Zorlu bir sorunun çözümü, hem sevinçle doldurdu hem de yorgunlukla beraber içimi hüzün kapladı.', 'duygu durumu karışık'),
    ('Hayal kırıklığı yaşamak, hem içimi hüzünle doldurdu hem de bir sonraki adıma motive etti.', 'duygu durumu karışık'),
    ('Beklenmedik bir durumla karşılaşmak, hem şaşkınlık hem de heyecanla içimi doldurdu.', 'duygu durumu karışık'),
    ('Kendimi yetersiz hissetmek, hem özgüven kaybıyla hem de bir sonraki adıma dair bir umutla içimi doldurdu.', 'duygu durumu karışık'),
    ('Geçmişteki hatıraları düşündükçe içim burkuluyor, o günleri özlemle hatırlıyorum.', 'üzgün'),
    ('Birinin yaşadığı acıyı görmek, içimi paramparça ediyor, onlara yardım edememenin acısıyla doluyum.', 'üzgün'),
    ('Onun anlattığı hikaye beni derinden üzdü, içimde bir boşluk oluştu.', 'üzgün'),
    ('Böyle trajik bir olayı duyunca içimde tarifsiz bir hüzün oluştu, üzüntüden kendimi alamadım.', 'üzgün'),
    ('Yalnızca birkaç kelimeyle anlattığı acı dolu geçmişi, içimi sarsıcı bir üzüntüyle doldurdu.', 'üzgün'),
    ('Onun duygularını anlayınca içimdeki üzüntü daha da derinleşti, ona yardım edebilmek için elimden geleni yapmak istiyorum.', 'üzgün'),
    ('Hayvanların yaşadığı acıyı görmek, içimi burkuyor ve onlara yardım edememenin üzüntüsüyle doluyum.', 'üzgün'),
    ('Bir insanın çektiği acıyı gördüğümde, içimde derin bir hüzün oluşuyor ve bu durumu değiştiremeyişimin üzüntüsünü yaşıyorum.', 'üzgün'),
    ('Bugün maalesef randevuya yetişemedim, beklenmedik bir durum oldu.', 'üzgün'),
    ('Maalesef, almak istediğim ürün stoklarda yoktu.', 'üzgün'),
    ('Güneşli bir günün tadını çıkarmak harika!', 'huzurlu'),
    ('Sevdiklerimle birlikte zaman geçirmek mutluluk verici.', 'mutlu'),
    ('Yeni bir şey öğrenmek heyecan verici!', 'heyecanlı'),
    ('Bir gülümsemeyle günümü aydınlatan insanlar var.', 'huzurlu'),
    ('Güzel bir manzara görmek içimi huzurla dolduruyor.', 'huzurlu'),
    ('Her sabah güne enerjik başlamak harika bir duygu.', 'huzurlu'),
    ('Olumlu düşünmek ruh halimi pozitif tutmama yardımcı oluyor.', 'mutlu'),
    ('Başkalarına yardım etmek içimi sevgiyle dolduruyor.', 'sevgi dolu'),
    ('Hayatta minik mutluluklar, büyük anlamlar taşır.', 'mutlu'),
    ('Yeni bir gün yeni fırsatlar demek, bu düşünce içimi aydınlatıyor.', 'mutlu'),
    ('Birisinin yüzünde gördüğüm gülümseme beni mutlu ediyor.', 'mutlu'),
    ('Hayatta olumlu şeylere odaklanmak beni daha mutlu kılıyor.', 'mutlu'),
    ('Basit bir tebessüm bile günümü aydınlatabilir.', 'mutlu'),
    ('Bir yeteneğimi geliştirmek beni motive ediyor.', 'mutlu'),
    ('Birisi için iyi bir şey yapmak harika bir duygu.', 'mutlu'),
    ('Kendimi yetersiz hissetmek, bu özgüvensizlik beni endişelendiriyor.', 'kaygılı'),
    ('Yakın arkadaşımın ani ölümü karşısında derin bir üzüntü yaşadım, bu acı içimi paramparça etti.', 'üzgün'),
    ('Gördüğüm bu manzara karşısında içim bir anda neşe dolu oldu, mutluluktan havalara uçuyormuşum gibi hissettim.', 'mutlu'),
    ('Aniden karşıma çıkan beklenmedik bir durum karşısında şaşkınlıktan donup kaldım, ne yapacağımı bilemedim.', 'şaşkın'),
    ('Son zamanlarda yaşadığım talihsiz olaylar ruh halimi olumsuz etkiledi, her şey çok zor görünüyor.', 'kaygılı'),
    ('Yarın gerçekleşecek olan heyecan verici etkinlik için sabırsızlanıyorum, içimdeki coşku giderek artıyor.', 'heyecanlı'),
    ('Birinin haksızlığa uğradığını gördüğümde içimde yükselen öfke duygusu beni kontrol altına almamı zorlaştırıyor.', 'öfkeli'),
    ('Bir anlık sessizlikte doğanın güzelliğini gözlemlemek benim için büyük bir pozitif enerji kaynağı oluyor.', 'huzurlu'),
    ('Beklenmedik bir hediye aldım.', 'şaşkın'),
    ('Birinin acı çektiğini görmek, içimi derin bir üzüntüyle dolduruyor.', 'üzgün'),
    ('Büyük bir heyecanla beklediğim şeyin nihayet benim.', 'heyecanlı'),
    ('Kaybolmuş gibi hissettiğim zamanlarda içsel dengeyi bulmak zor oluyor.', 'üzgün'),
    ('Doğanın güzellikleri karşısında hissettiğim derin huzur tarif edilemez bir duygu.', 'huzurlu'),
    ('Geleceğe dair belirsizlikler beni biraz endişelendiriyor, nötr olmak zor.', 'kaygılı'),
    ('Duyduğum sevinç, içimi neşeyle dolduruyor.', 'mutlu'),
    ('Bir kitabın sonunda karakterin acı çektiğini görmek beni üzgün hissettiriyor.', 'üzgün'),
    ('Beklenmedik bir telefonla yaşadığım şaşkınlık yüüzünden hala kendime gelemedim.', 'şaşkın'),
    ('Doğanın dinginliği içinde kaybolmak, içsel huzurun en güzel hali.', 'huzurlu'),
    ('Birinin haksızlığa uğraması karşısında içimde yanan öfke duygusu kontrolümü zorluyor.', 'öfkeli'),
    ('Geçmişteki olumsuz deneyimler, şu anki ruh halimi kötü etkiliyor.', 'üzgün'),
    ('Birinin başarısı karşısında duyduğum içten sevinç, beni mutlu ediyor.', 'mutlu'),
    ('Kendimi huzursuz hissettiğimde doğaya çıkıp huzur bulmak harika bir his.', 'pozitif'),
    ('Bir süredir devam eden stresli günler, beni kaygılandırıyor.', 'kaygılı'),
    ('Sevdiklerimle geçirdiğim keyifli zamanlar, içimi mutlulukla dolduruyor.', 'mutlu'),
    ('Yıldızların altında yürümek, içsel huzurun en saf halini hissettiriyor.', 'huzurlu'),
    ('Doğanın sesini dinlerken, kuşların melodisi ruhumu huzurla dolduruyor.', 'huzurlu'),
    ('Beklenmedik bir anda karşılaştığımız eski bir dost, yüzümde tebessümle birlikte içimi sıcacık bir neşeyle doldurdu, uzun zamandır hissetmediğim bir mutlulukla karşılaştım.', 'mutlu'),
    ('Büyük bir şaşkınlıkla karşılaşınca ilk tepkim donup kalmak oldu, etrafıma baktığımda ise yaşadığım şaşkınlık beni içsel bir coşkuyla sarıp sarmaladı.', 'şaşkın'),
    ('Sakin bir akşam yürüyüşünde yaşadığım huzur, içimdeki dinginlik hissiyatını artırarak adeta ruhumu yeniledi, hayatın akışına kendimi bırakmış hissettim.', 'huzurlu'),
    ('Yoğun bir günün ardından sessizliğe gömülmek, içsel huzurun en derinine inmeme neden oluyor, bu sessizlikte kaybolmak adeta ruhumu dinlendiriyor.', 'huzurlu'),
    ('Derin bir üzüntü içinde kaybolmuş gibi hissettiğim anlarda, içsel dengeyi yeniden kurmak için doğaya kaçıyorum.', 'üzgün'),
    ('Güneşli bir gün, içimi mutlulukla doldurdu.', 'mutlu'),
    ('Bir projeyi tamamladığımda hem mutlu hem de biraz endişeliydim.', 'duygu durumu karışık'),
    ('Beklenmedik bir hediye aldığımda hem sevinçli hem de biraz şaşkın hissetmiştim.', 'duygu durumu karışık'),
    ('Hayalini kurduğum bir işi başarmak için yoğun bir şekilde çalışırken, hem gurur duyuyor hem de yorgun hissediyordum.', 'duygu durumu karışık'),
    ('Gelecek planları yaparken hem heyecanlı hem de biraz endişeliydim.', 'duygu durumu karışık'),
    ('Bir konuda kararsız kaldığımda hem belirsizlik hissiyle hem de biraz gerginlikle doluydum.', 'duygu durumu karışık'),
    ('Bir kitap okurken huzur buldum.', 'huzurlu'),
    ('Beklenmedik bir telefon, şaşkınlık yarattı.', 'şaşkın'),
    ('Yağmurlu bir günde yalnız olmak, içimi hüzün kapladı.', 'üzgün'),
    ('Karanlıkta bir ses duyunca korktum.', 'korkmuş'),
    ('Tartışma, öfke yarattı.', 'öfkeli'),
    ('Birinin acı çektiğini görmek üzdü.', 'üzgün'),
    ('Güzel bir gün.', 'mutlu'),
    ('Yemek yemek mutlu eder.', 'mutlu'),
    ('Yaşasın! Yeni bir kitap aldım.', 'mutlu'),
    ('Köpekler havlayarak üzerime gelince korkudan altıma yaptım.', 'korkmuş'),
    ('Trafik öfke yaratabilir.', 'öfkeli'),
    ('Çiçekler mutluluk verir.', 'mutlu'),
    ('Basit bir hediye, örneğin bi çikolata bie beni kolayca mutlu edebilir.', 'mutlu'),
    ('Korkutucu bir film izlemek korku yaratabilir.', 'korkmuş'),
    ('Gülmek mutlu eder.', 'mutlu'),
    ('Onun yaşadıklarını duyunca içim burkuldu.', 'üzgün'),
    ('Ayağım burkulduğunda canım çok acıdı.', 'üzgün'),
    ('O acı gerçekleri öğrendiğimde içim burkuldu.', 'üzgün'),
    ('Onun başından geçenler karşısında içim burkuldu.', 'üzgün'),
    ('Bisiklet sürmeye bayılıyorum.', 'mutlu'),
    ('Beklenmedik haberler şaşırtıcı olabilir.', 'şaşkın'),
    ('Bir kedinin miyavlaması bile beni mutlu etmek için yeterli.', 'mutlu'),
    ('Karanlık odalar korkutucu olabilir.', 'korkmuş'),
    ('Başarıya ulaşmak heyecan verici olabilir.', 'heyecanlı'),
    ('Sessizlik sakinlik getirir.', 'huzurlu'),
    ('Evdeki bu gerginlik öfke yaratabilir.', 'öfkeli'),
    ('Deniz kenarında oturmak huzur verir.', 'pozitif'),
    ('Yemekteyken çatkapı gelen beklenmedik misafirlerden dolayı elim ayağıma dolaştı.', 'şaşkın'),
    ('Yeni bir hobi edinmek heyecan verici olabilir.', 'heyecanlı'),
    ('Bir yarışmada birinci olmak heyecan verici bir deneyimdir.', 'heyecanlı'),
    ('Yakın zamanda gerçekleşecek etkinlik beni çok heyecanlandırıyor.', 'heyecanlı'),
    ('Bir insanın yaşadığı acıyı gördüğümde, içimde bir şeyler burkuluyor.', 'üzgün'),
    ('Olayları öğrendiğimde içimde tarifsiz bir burukluk hissi oluştu.', 'üzgün'),
    ('İzlediğim o duygusal film yüzünden hüngür hüngür ağladım.', 'üzgün'),
    ('İzlediğim dizinin yeni bölümünün yayınlanmasını beklerken içim kıpır kıpır oluyor.', 'heyecanlı'),
    ('Üniversite için yaşadığım şehirden ayrılırken sevdiğim insanlarla vedalaşmak beni çok üzüyor.', 'üzgün'),
    ('Çok sevdiğim bilekliğimi kaybettim.', 'üzgün'),
    ('Sevdiklerimden uzakta olmaktan nefret ediyorum', 'üzgün'),
    ('Beklenmedik bir ses duyunca korktum.', 'korkmuş'),
    ('Gece vakti ıssız bir sokakta yürümek özellikle kadınlar için hem tehlikeli hem de korkunç olabilir..', 'korkmuş'),
    ('Gördüğüm kabus yüzünden hararetli bir şekilde uyandım.', 'korkmuş'),
    ('Merhaba.', 'nötr'),
    ('Nasılsın?', 'nötr'),
    ('İyi misin?', 'nötr'),
    ('Yüksek bir dağın zirvesine tırmandığımda içimde tarifsiz bir heyecan vardı.', 'heyecanlı'),
    ('Ben onu çok seviyorum.', 'sevgi dolu'),
    ('Durum karışık, hem sevinçli hem de endişeli hissediyorum.', 'duygu durumu karışık'),
    ('Uzun bir yolculuktan sonra sevdiklerimle buluşmak beni hem mutlu etti hem de biraz yorgun düşürdü, ancak onlarla bir araya gelmek içimi huzurla doldurdu.', 'duygu durumu karışık'),
    ('Beklenmedik bir şekilde karşılaştığımız sürpriz parti bana hem şaşkınlık hem de büyük bir mutluluk yaşattı, fakat bir yandan da böyle bir etkinliğe hazırlıksız olmak biraz endişe yarattı.', 'duygu durumu karışık'),
    ('Yoğun bir iş gününden sonra eve geldiğimde hem huzur aradım hem de biraz yorgun hissettim, ama evdeki sakin atmosfer içimi rahatlattı.', 'duygu durumu karışık'),
    ('Bir anlık karar sonucu alınan ani bir seyahat kararı beni hem heyecanlandırdı hem de biraz endişelendirdi, ancak yeni bir yer keşfetme düşüncesi içimi coşturdu.', 'duygu durumu karışık'),
    ('Yaşadığımız beklenmedik olay hem şaşkınlık yarattı hem de hüzünlendirdi, ancak bu durumun üstesinden gelme çabası içimi biraz da olsa rahatlattı.', 'duygu durumu karışık'),
    ('Maalesef, planladığımız piknik yağmur yüzünden iptal oldu.', 'üzgün'),
    ('Bugün maalesef geç kaldım, yoğun trafik nedeniyle işe zamanında yetişemedim.', 'üzgün'),
    ('Maalesef, kaybettiğimiz maç bizi biraz üzdü ama önemli olan deneyimdi.', 'üzgün'),
    ('Tatil için planladığımız seyahati maalesef finansal sıkıntılar nedeniyle ertelemek zorunda kaldık.', 'üzgün'),
    ('Maalesef, beklenmedik bir aksilik nedeniyle toplantıya katılamayacağım.', 'üzgün'),
    ('Maalesef, planladığımız etkinlik hava koşulları sebebiyle ertelendi.', 'üzgün'),
    ('Hava durumu ile ilgili duyarsızım.', 'nötr'),
    ('Farklı bir müzik türü dinlemek bana bir şey hissettirmez.', 'nötr'),
    ('Yeni bir restoranda yemek yemek benim için olağan bir deneyimdir.', 'nötr'),
    ('Bazı insanlarla olan etkileşimlerim duygusal olarak etkilemez beni.', 'nötr'),
    ('Saatlerce süren toplantılar benim için sadece rutin bir iş görevidir.', 'nötr'),
    ('Öğrenciler arasındaki sürekli çatışmalar benim için öfke dolu anlardı.', 'öfkeli'),
    ('Ondan nefret ediyorum.', 'öfkeli'),
    ('İçim öfke ve nefretle dolu.', 'öfkeli'),
    ('Büyük bir maç öncesi yaşadığım heyecan, beni adeta bir enerji patlamasıyla doldurmuştu.', 'heyecanlı'),
    ('Adaletin olmadığı durumlar beni öfkelendiriyor.', 'öfke'),
    ('Sorunları çözmek için daha fazla zaman gerekiyor, kızgınım.', 'öfke'),
    ('Yakın zamanda öğrendiğim bir haber beni oldukça şaşırttı.', 'şaşkın'),
    ('Bir anda yaşanan değişiklik şaşkınlık yaratabilir.', 'şaşkın'),
    ('Aniden karşıma çıkan bu durum beni şaşkına çevirdi.', 'şaşkın'),
    ('Bir haksızlık karşısında öfke duymak normaldir.', 'öfkeli'),
    ('Beklenmedik bir durumda sinirlenmek kaçınılmaz.', 'öfkeli'),
    ('Sürekli gecikmeler öfke yaratabilir.', 'öfkeli'),
    ('Birinin sözlerine tepki vermemek bazen öfkeyi artırabilir.', 'öfkeli'),
    ('Anlayışsızlık ve hoşgörüsüzlük öfke hissiyatı uyandırabilir.', 'öfkeli'),
    ('Adaletsiz bir durum karşısında öfkelenmek doğal.', 'öfkeli'),
    ('Beklenmedik bir şekilde karşılaşılan engeller sinir bozabilir.', 'öfkeli'),
    ('Merhaba sevgilim, bugün nasılsın?', 'nötr'),
    ('İyi değilim Ayşe, işsiz kalmaktan dolayı kendimi kötü hissediyorum.', 'üzgün'),
    ('Sakın üzülme Ali, ben buradayım. Seninle birlikte bu zorlu süreci atlatırız.', 'duygu durumu karışık'),
    ('Teşekkür ederim Ayşe, seninle birlikte olduğum için kendimi şanslı hissediyorum.', 'mutlu'),
    ('Ben de seninle birlikte olmaktan mutluluk duyuyorum.', 'mutlu'),
    ('Arkadaşlarımla birlikte güzel bir gün geçirdim.', 'mutlu'),
    ('Yeni bir yemek tarifi denedim ve çok beğendim.', 'mutlu'),
    ('Bugün trafikte çok zaman kaybettim.', 'öfkeli'),
    ('Yeni bir film izledim ve beğendim.', 'mutlu'),
    ('Seninle birlikte olduğum için ben de kendimi daha güçlü hissediyorum. Seni seviyorum Ali.', 'sevgi dolu'),
    ('Sevgi, evrenin en güçlü ve büyüleyici duygularından biridir. Kalpler arasında derin bağlar kurarak insanları birbirine bağlar, hayatın anlamını şekillendirir. Sevgi, sabır, anlayış, özveri ve saygıyla yoğrulmuş bir duygudur. Birinin mutluluğu için kendi mutluluğunu göz ardı edebilmektir. Sevgi, karanlık günlerde bir ışık, zor zamanlarda bir destek olabilir. Bir bakışta, bir dokunuşta, söylenen bir sözde veya sadece sessiz bir anın paylaşımında bulunabilir. Sevgi, tüm insanlığın ortak dilidir ve dünyayı daha iyi bir yer haline getirebilir. Her kalpte var olan bu güçlü duygu, sevginin sonsuzluğunu ve insan ruhundaki derin etkisini yansıtır.', 'sevgi dolu'),
    ('Tiksinme duygusu, insanın içsel bir tepkisi olarak ortaya çıkar ve genellikle hoşlanılmayan bir durum veya şey karşısında hissedilir. Bu duygu, bazen bir koku, görüntü, davranış veya durumla tetiklenebilir. Vücut, tiksinme hissiyle, olumsuz veya rahatsız edici bir durumu reddetme eğilimindedir. Tiksinme, insanın içgüdüsel bir şekilde kendini koruma mekanizması olarak da işlev görür. Bu duygu, bireyi zararlı veya tehlikeli olarak algılanan şeylerden uzak durmaya yönlendirir. Tiksinme duygusu, kişisel sınırları koruma, hijyen ve sağlık gibi önemli konularda bireye yardımcı olabilir. Ancak bu duygu, kişiden kişiye değişebilir ve kültürel farklılıklara göre şekillenebilir.', 'tiksinmiş'),
    ('Yolda yürürken ani bir koku burnuma geldi ve içimden gelen tiksinme duygusuyla birlikte hemen uzaklaşmak istedim. O koku, o kadar keskin ve rahatsız ediciydi ki adımımı hızlandırmak ve uzaklaşmak için her şeyi yapabilirdim. Bu tiksinme duygusu, kokuyla ilişkilendirilmiş bir rahatsızlık hissiydi; sanki vücudum, o kokuyla temas etmek istemiyordu ve ben de kendimi uzaklaştırmak için anında bir tepki verdim.', 'tiksinmiş'),
    ('Huzur, ruhun derinliklerinde dinginlik ve içsel bir denge hissiyatı yaratan bir duygu durumudur. Doğanın kucaklayıcı sessizliği içinde bir akşamüstü, yumuşak esen rüzgarın eşliğinde hissedilen huzur, benzersiz bir an olabilir. Zihninizdeki gürültülerin yerini sessiz düşünceler alır, kalp atışlarınız yumuşar ve çevrenizdeki her şey adeta bir uyum içinde dans eder gibi görünür. Huzur, kendinizi olduğunuz gibi kabul etme, anın tadını çıkarma ve yaşamın koşuşturmacasından uzaklaşma hissi verir. Bazen sadece bir kitabın sayfaları arasında kaybolmak, içsel sessizliği bulmak için yeterli olabilir. Huzur, içsel bir dinginlik ve mutluluk kaynağıdır; insanın kendini olduğu gibi hissettiği, dış etkenlerin iç huzuru bozamadığı nadir anlardan biridir.', 'huzurlu'),
    ('Yıldızlar, gökyüzünü süsleyen masmavi bir geceye yayılmıştı. Küçük bir kasabanın sakin sokakları, sessizlik içinde huzurlu bir uyku içindeydi. Kasabanın kenarındaki eski çınar ağacının altında, yaşlı bir adam her gece olduğu gibi oturmuş, gözlerini yıldızlara dikmişti.', 'huzurlu'),
    ('O gece, genç bir kız çocuğu olan Leyla, Dedem Ahmet’in yanına sessizce yaklaştı. Ahmet, kızın yaklaşan adımlarını duydu ve gülümsedi. Leyla, Ahmet’in hikayelerini dinlemeyi çok severdi.', 'mutlu'),
    ('Kızım, bu kasabanın geçmişi, birbirinden güzel hikayelerle dolu. Bilir misin, burada yıllar önce yaşanan bir olay vardı. Kasabanın köşesindeki eski bir evde yaşayan bir aile vardı. Bu aile, herkes tarafından sevilirdi.', 'mutlu'),
    ('Huzur, iç huzuru, sakinlik, rahatlık, dinginlik gibi anlamlara gelen bir duygudur. Huzurlu olmak, kişinin hem fiziksel hem de zihinsel olarak rahat ve sakin hissetmesi anlamına gelir. Huzurlu bir insan, endişesiz, stressiz ve tedirginlik hissetmez. Zihninde karmaşa yoktur ve düşünceleri nettir.', 'huzurlu'),
    ('Tiksinme, bir şeyden veya bir durumdan derin bir tiksinti ve iğrenme duyma duygusudur. Bu duygu, fiziksel veya duygusal olarak ortaya çıkabilir. Fiziksel tiksinme, genellikle bir şeyin görünümü, kokusu veya tadı gibi duyusal uyaranlarla tetiklenir. Örneğin, bozulmuş bir yiyecek veya pis bir ortam tiksinti uyandırabilir. Duygusal tiksinme ise, genellikle bir kişinin davranışları, düşünceleri veya değerleri gibi bir şeyle ilgili olumsuz duygularla tetiklenir. Örneğin, bir kişinin yalan söylemesi veya başkalarına zarar vermesi tiksinti uyandırabilir.', 'tiksinmiş'),
    ('Seninle tanıştığıma çok memnun oldum, bana çok iyi davrandın.', 'sevgi dolu'),
    ('Sınavı başarıyla geçtim, çok mutluyum.', 'mutlu'),
    ('Yarın seyahate çıkacağız, çok heyecanlıyım.', 'heyecanlı'),
    ('Ormanda yürüyüş yapmak bana huzur veriyor, doğanın seslerini dinliyorum.', 'huzurlu'),
    ('Bu hediyeyi bana kim gönderdi, çok şaşırdım.', 'şaşkın'),
    ('Bugün hava nasıl, çok sıcak mı?', 'nötr'),
    ('Bugün hem sevindim hem üzüldüm, duygularım karışık.', 'duygu durumu karışık'),
    ('Köpeğim kayboldu, çok üzgünüm.', 'üzgün'),
    ('Karanlıktan korkuyorum, yanımda kalır mısın?', 'korkmuş'),
    ('Senin yüzünden işimi kaybettim, çok öfkeliyim.', 'öfkeli'),
    ('Salgın nedeniyle çok kaygılıyım, sağlığımı korumak için ne yapmalıyım?', 'kaygılı'),
    ('Bu yemek çok kötü kokuyor, tiksindim.', 'tiksinmiş'),
    ('Ailemle birlikte geçirdiğim anlar her zaman sevgi dolu.', 'sevgi dolu'),
    ('Arkadaşlarımla güzel bir gün geçirdik, çok mutluyum.', 'mutlu'),
    ('Beklenen tatilimiz yarın başlıyor, çok heyecanlıyım!', 'heyecanlı'),
    ('Doğanın ortasında sessiz bir piknik, insanı huzurlu hissettiriyor.', 'huzurlu'),
    ('Beklenmedik bir sürprizle karşılaştım ve adeta şaşkına döndüm.', 'şaşkın'),
    ('Günlük rutinimi sürdürüyorum, herhangi bir özel duygu yok.', 'nötr'),
    ('İş yerindeki değişiklikler beni hem heyecanlandırıyor hem de endişelendiriyor.', 'duygu durumu karışık'),
    ('Sevdiğim birini kaybetmenin üzüntüsü içindeyim.', 'üzgün'),
    ('Gece karanlığında aniden bir ses duydum, korkmuş hissettim.', 'korkmuş'),
    ('Adaletsiz bir durumla karşılaştım ve bu beni öfkelendirdi.', 'öfkeli'),
    ('Yaklaşan sınav nedeniyle biraz kaygılıyım, başarılı olabilecek miyim endişesi var.', 'kaygılı'),
    ('O yemeği tattıktan sonra tiksinmiş bir şekilde geri koydum.', 'tiksinmiş'),
    ('Arkadaşlarımın sürpriz doğum günü partisiyle adeta şaşkına döndüm.', 'şaşkın'),
    ('Annemi çok seviyorum', 'sevgi dolu'),
    ('Yarın yapmam gereken sunum için kaygılıyım, acaba başarılı olabilecek miyim?', 'kaygılı'),
    ('Deniz kenarında oturup gün batımını izlemek insana huzur veriyor.', 'huzurlu'),
    ('Yeni işimdeki adaletsizlik beni sinirlendiriyor.', 'öfkeli'),
    ('Karşılaştığımız durum, nötr bir tepkiyle karşılandı.', 'nötr'),
    ('Tiksinmiş bir şekilde o yemeği yedim.', 'tiksinmiş'),
    ('Bu kitabı sonunda bitirebildim.', 'mutlu'),
    ('İyi bir kitap okumak her zaman huzurlu bir deneyimdir.', 'huzurlu'),
    ('Hayalini kurduğumuz tatil sonunda gerçekleşecek, heyecanlıyım!', 'heyecanlı'),
    ('Bugün iş yerindeki adaletsizlik beni öfkelendirdi.', 'öfkeli'),
    ('Her şey yolunda giderken ansızın oluşan bir durum, nötr bir tepkiyle karşılandı.', 'nötr'),
    ('Son zamanlarda yaşadığım karışık duygular beni içsel olarak etkiliyor.', 'duygu durumu karışık'),
    ('Uzun zamandır görmediğim eski arkadaşımla karşılaşınca sevinçten havalara uçtum.', 'mutlu'),
    ('Büyük bir kaybın ardından duygu durumum oldukça üzgündü.', 'üzgün'),
    ('Gece karanlığında yürürken ani bir ses duydum, korkmuş hissettim.', 'korkmuş'),
    ('Yarın yapılacak önemli bir toplantı için kaygılıyım.', 'kaygılı'),
    ('Bir restoranda servis edilen yemeği tattıktan sonra tiksinmiş bir şekilde geri çevirdim.', 'tiksinmiş'),
    ('Birinci romanını yazarken yazarın iç dünyasına dalmak oldukça zordur.', 'duygu durumu karışık'),
    ('Yüksek dağların zirvesine tırmanmak, beni heyecanlandırıyor.', 'heyecanlı'),
    ('Eski fotoğraflara bakarken geçmişe duyulan özlem, içimi hüzünle dolduruyor.', 'üzgün'),
    ('Tatilde plajda kitap okumak, benim için tam bir huzur kaynağıdır.', 'huzurlu'),
    ('Yoğun iş temposu altında çalışmak, zamanla stres ve kaygıya neden oluyor.', 'kaygılı'),
    ('Yeni bir dil öğrenmek, hem zorlayıcı hem de heyecan verici bir deneyimdir.', 'heyecanlı'),
    ('Bir konserde sevdiğim sanatçının şarkısını canlı dinlemek, beni mutlu eder.', 'mutlu'),
    ('Uzun bir koşu sonrasında duyulan hafif yorgunluk, beni rahatlamış hissettirir.', 'huzurlu'),
    ('Güzel bir film izlemek, duygusal bir bağ kurmama neden olabilir.', 'duygu durumu karışık'),
    ('Evde yapılan yemeklerin lezzeti, dışarıda yemek yemekten daha özel olabilir.', 'mutlu'),
    ('Uzun bir doğa yürüyüşü sonrasında ormanda kamp kurmak, beni huzurlu hissettirir.', 'huzurlu'),
    ('Bir sergiyi gezerken sanat eserlerini incelemek, içsel bir keşif yolculuğuna benzer.', 'duygu durumu karışık'),
    ('Birinci sınıf bir restoranda lezzetli bir akşam yemeği yemek, keyif verici bir deneyimdir.', 'mutlu'),
    ('Yoğun bir günün ardından evde sessizce oturmak, sakinleştirici bir etki yapar.', 'huzurlu'),
    ('Bungee jumping yapmak, hem heyecanlı hem de korkutucu bir deneyim olabilir.', 'heyecanlı'),
    ('Bir sevdik kaybetmenin acısı, duygusal olarak derin bir etki bırakabilir.', 'üzgün'),
    ('Yoğun bir konser kalabalığında sevdiğim müzikleri dinlemek, enerjimi yükseltir.', 'heyecanlı'),
    ('Bir romanın içine dalmak ve karakterlerle bağ kurmak, beni o dünyaya çeker.', 'duygu durumu karışık'),
    ('Bir spor müsabakasında favori takımımın galibiyeti, sevinci doruklara çıkarır.', 'mutlu'),
    ('Bir problemi çözdüğümde hissettiğim başarı duygusu, beni motive eder.', 'mutlu'),
    ('Bir haftalık dağ trekkingi sonunda zirveye ulaşmak, hem fiziksel hem de duygusal bir zaferdir.', 'heyecanlı'),
    ('Eski bir dostla kahve içip geçmişi anlatmak, nostaljik bir duygu yaratır.', 'duygu durumu karışık'),
    ('Bir yaz günü plajda kitap okurken dalgaların sesini dinlemek, sakinlik verici bir deneyimdir.', 'huzurlu'),
    ('Yabancı bir ülkede kaybolmak ve yerel kültürle tanışmak, macera dolu bir deneyim sunar.', 'heyecanlı'),
    ('Bir konser sırasında sevilen şarkıyı canlı dinlemek, duygusal bir coşku yaratır.', 'mutlu'),
    ('Bir gönüllü çalışmada yer almak ve başkalarına yardım etmek, içsel bir memnuniyet sağlar.', 'mutlu'),
    ('Doğanın içinde kamp kurmak, çevresel seslerle bütünleşerek huzurlu bir atmosfer yaratır.', 'huzurlu'),
    ('Bir sanat galerisinde farklı dönemlere ait eserleri incelemek, estetik bir keyif sunar.', 'duygu durumu karışık'),
    ('Bir filmi izlerken karakterlerle empati yapmak, duygusal bir bağ kurmayı sağlar.', 'duygu durumu karışık'),
    ('Yeni bir beceri öğrenmek ve bu alanda ilerleme kaydetmek, kişisel gelişimi teşvik eder.', 'mutlu'),
    ('Bir restoranda kötü kokan bir yemek yemekten sonra tiksinç bir duygu içindeyim.', 'tiksinmiş'),
    ('Adaletsiz bir durumla karşılaşmak, içimde öfke ve hayal kırıklığı yaratıyor.', 'öfkeli'),
    ('Sevdiğim birini kaybetmenin acısı, kalbimi derin bir üzüntüyle dolduruyor.', 'üzgün'),
    ('Trafikte sıkışıp kalmak ve geç kalma riski, sinirimi zorlayan bir durum yaratıyor.', 'öfkeli'),
    ('Eski fotoğraflara bakarken geçmişteki güzel anıları hatırlamak, içimi hüzünle dolduruyor.', 'üzgün'),
    ('Çok beklediğim bir konserin iptal olması, büyük bir hayal kırıklığına neden oldu.', 'üzgün'),
    ('Birisiyle anlaşmazlık yaşamak ve onunla iletişim kuramamak, öfkeyle dolu bir durum yaratıyor.', 'öfkeli'),
    ('Kirli bir restoran tuvaletiyle karşılaşmak, içimde tiksinti ve rahatsızlık yaratıyor.', 'tiksinmiş'),
    ('Bir yakınımın haksızlığa uğraması, hem öfke hem de üzüntü hissi uyandırıyor.', 'öfkeli'),
    ('Bir sevdiğimin sözlerinden etkilenip ağlamak, içsel bir üzüntüye neden oluyor.', 'üzgün'),
    ('Uzun bir günün ardından eve dönüp köpeğimle oyun oynamak, içimi sevgiyle doldurur.', 'mutlu'),
    ('Haksız bir eleştirinin hedefi olmak, hem öfkeli hem de üzgün hissetmeme neden oluyor.', 'duygu durumu karışık'),
    ('Bir doğal afet sonrasında yardım etmek için gönüllü olmak, duygusal bir memnuniyet yaratır.', 'mutlu'),
    ('Bir yakınımın başarısını görmek, hem gurur hem de mutluluk duygusu uyandırır.', 'mutlu'),
    ('Dürüstlüğün karşılığını alamamak, güven kaybına ve içsel bir hüsran hissine neden olabilir.', 'üzgün'),
    ('Bir sanat eserini anlamak için uzun süre önünde durmak, derin düşüncelere sevk edebilir.', 'duygu durumu karışık'),
    ('Haksız bir suçlamayla karşılaşmak, hem öfke hem de hüzün hissettirir.', 'duygu durumu karışık'),
    ('Bir sevilenin beklenmedik kaybı, derin bir acı ve boşluk bırakabilir.', 'üzgün'),
    ('Bir arkadaşımın başarısızlığı karşısında onun acısını paylaşmak, empati ve üzüntü yaratır.', 'üzgün'),
    ('Huzurlu bir günün ardından güneşin batışını izlemek, içsel bir dinginlik sağlar.', 'huzurlu'),
    ('Bir restoranda sipariş ettiğim yemeği tattıktan sonra midesim bulandı, tiksinmiş bir şekilde masadan kalktım.', 'tiksinmiş'),
    ('Adaletsiz bir durumla karşılaşmak, içimi öfke ve hayal kırıklığıyla dolduruyor. Duygusal bir patlama hissediyorum.', 'öfkeli'),
    ('Sevdiğim birinin beklenmedik ölümü karşısında, derin bir üzüntü içindeyim. Kayıp büyük ve çaresiz hissediyorum.', 'üzgün'),
    ('Bir iş görüşmesinde haksız bir şekilde değerlendirilmek, öfke ve hüsran içindeyim. Hak ettiğim değeri görememek beni üzüyor.', 'öfkeli'),
    ('Bir arkadaşımın ihaneti karşısında duyduğum iğrençlik hissi, içimi tiksinçlikle dolduruyor. Güven kaybı büyük bir yara açtı.', 'tiksinmiş'),
    ('Bir sevdik kaybetmenin acısı, içsel bir karanlık ve üzüntüyle dolu. Boşluğu doldurmak zor, her şey gri görünüyor.', 'üzgün'),
    ('Birisiyle anlaşmazlık yaşamak ve onunla iletişim kuramamak, öfke ve hayal kırıklığı içinde bir izolasyon hissi yaratıyor.', 'öfkeli'),
    ('Kirli bir restoran tuvaletiyle karşılaşmak, içimi tiksinti ve rahatsızlıkla dolduruyor. Sağlıksız koşullar beni rahatsız ediyor.', 'tiksinmiş'),
    ('Bir başarımdan dolayı hak ettiğim takdiri alamamak, hem öfkeli hem de üzgün hissettiriyor. Adil bir değerlendirme beklerken hayal kırıklığı yaşıyorum.', 'duygu durumu karışık'),
    ('Bir sevilenin beklenmedik kaybı, içsel bir boşluğa neden oluyor. Zaman içinde bu kaybı kabullenmek çok zor ve duygusal bir sarsıntı yaratıyor.', 'üzgün'),
    ('Bir kitap okurken beklenmedik bir karakter ölümüyle karşılaşmak, içsel bir hüzün ve şok hissi yaratır.', 'üzgün'),
    ('Bir arkadaşın başarısızlığı karşısında onun acısını paylaşmak, hem empati hem de derin bir üzüntü yaratır.', 'üzgün'),
    ('Bir projede çalışırken ekip üyeleri arasında yaşanan çatışma, içimi gerginlik ve öfkeyle doldurur.', 'öfkeli'),
    ('Uzun süreli bir ilişkinin sona ermesi, içimi bir boşluk ve kalp kırıklığıyla doldurur.', 'üzgün'),
    ('Bir yakınımın haksızlığa uğraması, içimi hem öfke hem de adaletsizlik duygusuyla doldurur.', 'öfkeli'),
    ('Bir sanat eserini anlamak ve hissetmek, duygusal bir bağ kurmayı sağlar ve içimi coşkuyla doldurur.', 'mutlu'),
    ('Bir doğal felaketin yaşandığı bir bölgeye yardım etmek, içsel bir tatmin ve mutluluk hissi yaratır.', 'mutlu'),
    ('Bir sevilenin aniden kaybolması, içsel bir boşluğa ve derin bir üzüntüye neden olur.', 'üzgün'),
    ('Bir sevilenin başarılarına tanık olmak, içimi gurur ve mutlulukla doldurur.', 'mutlu'),
    ('Birini kandırılmış hissetmek, içimi hem öfke hem de hayal kırıklığıyla doldurur.', 'öfkeli'),
    ('Arkadaşlarımın sürpriz doğum günü partisiyle adeta şaşkına döndüm.', 'şaşkın'),
    ('Annemi çok seviyorum', 'sevgi dolu'),
    ('Yarın yapmam gereken sunum için kaygılıyım, acaba başarılı olabilecek miyim?', 'kaygılı'),
    ('Deniz kenarında oturup gün batımını izlemek insana huzur veriyor.', 'huzurlu'),
    ('Yeni işimdeki adaletsizlik beni sinirlendiriyor.', 'öfkeli'),
    ('Karşılaştığımız durum, nötr bir tepkiyle karşılandı.', 'nötr'),
    ('Tiksinmiş bir şekilde o yemeği yedim.', 'tiksinmiş'),
    ('Bu kitabı sonunda bitirebildim.', 'mutlu'),
    ('Arkadaşlarımla yaşadığım bir anıyı hatırlayınca duygusal bir karışıklık hissettim.', 'duygu durumu karışık'),
    ('Sevdiğim biri bugün vefat etti.', 'üzgün'),
    ('Gece karanlığında yürürken garip sesler duyarak korkmuş hissettim.', 'korkmuş'),
    ('Yarınki tatil planı için çok heyecanlıyım!', 'heyecanlı'),
    ('Babamı çok seviyorum', 'sevgi dolu'),
    ('Maalesef sınavımdan beklediğimden daha düşük bir not aldım.', 'üzgün'),
    ('Dışarıda hükümet konusu açıldığında görüşümü belirtmeyerek tarafsız bir tutum sergiliyorum.', 'nötr'),
    ('Geleceğimle ilgili belirsizliklerden dolayı oldukça endişeliyim.', 'kaygılı'),
    ('Yarınki tatil planı için çok heyecanlıyım, harika bir gün geçireceğim!', 'duygu durumu karışık'),
    ('Harika bir gün beni bekliyor.', 'mutlu'),
    ('İzlediğim korku filmi yüzünden yatağa girdiğimde etrafımdaki karanlık beni çok korkuttu.', 'korkmuş'),
    ('Bugün yeni bir işe başladığım için içim kıpır kıpır.', 'heyecanlı'),
    ('Arkadaşımın sıktığı şekerli parfüm çok iğrenç kokuyor.', 'tiksinmiş'),
    ('Kedimin babama olan bağlılığı beni hayrete düşürdü.', 'şaşkın'),
    ('Annemin abime sergilediği tutumdan dolayı kıskançlıktan çılgına döndüm.', 'öfkeli'),
    ('Doğada yürüyüş yapmak gibisi yok.', 'huzurlu'),
    ('En yakınlarımı giderek kaybediyorum.', 'üzgün'),
    ('Kedimi her gördüğümde yeniden aşık oluyorum.', 'sevgi dolu'),
    ('Verdiğim emeklerin karşılığını aldım ve sınavı kazandım.', 'mutlu'),
    ('Bana veya başkalarına yapılan haksızlıklar beni çok sinirlendiriyor.', 'öfkeli'),
    ('Doktorların öldüğünü söylediği hasta, hayata döndü. Bu bir mucize.', 'şaşkın'),
    ('Ondan beklemediğim bu hareket karşısında ne hissedeceğimi bilemedim.', 'duygu durumu karışık'),
    ('Gelen bomba ihbarı hepimizi çok korkuttu.', 'korkmuş'),
    ('O çöp tenekesinin kapağını açtığımda midem bulandı, hemen kapağı kapatıp oradan uzaklaştım.', 'tiksinmiş'),
    ('Antreman sonrası yaptığım sıcak duş, beni çok rahatlatıyor.', 'huzurlu'),
    ('İlk kez uçağa bineceğim için çok heyecanlıyım.', 'heyecanlı'),
    ('Merhaba! Bugün nasılsınız?', 'nötr'),
    ('İş görüşmelerine gitmek beni çok geriyor.', 'kaygılı'),
    ('Her ne kadar halsiz ve yorgun olsam da konu gezmek olunca hiçbir şeyim yokmuş gibi mutlu mesut etrafta geziyorum.', 'duygu durumu karışık'),
    ('Bana her sarıldığında annemin yüzünde oluşan o sevgi dolu gülümseme, bana her şeyin üstesinden gelebileceğimi hatırlatıyor.', 'sevgi dolu'),
    ('Çevremdekilerin beni anlamaması yüzünden sürekli ağlıyorum.', 'üzgün'),
    ('Denizde yüzerken huzurla içimi dolduran bir sessizlik, beni kendi dünyama çekti. Doğanın güzelliğini seyrederken kendimi derin suların akışına bıraktım.', 'huzurlu'),
    ('Toplantıda yaşanan o derin sessizlik, beni çok gerdi.', 'kaygılı'),
    ('Onu her gördüğümde kalbim yerinden çıkacak gibi oluyor.', 'heyecanlı'),
    ('Bir çocuğun yüzündeki o masum mutluluk, oynadığı oyuncaklarla doldurduğu oyun odasında saklıydı. Her bir kahkahası, odanın içine neşyle dolduruyor.', 'mutlu'),
    ('Bir mucizeye tanık olurken, şaşkınlıkla gözlerini ovuşturuyor ve inanılması güç bir gerçeklikle karşı karşıya olduğunu düşünüyorsun.', 'şaşkın'),
    ('Dengeli bir ruh haliyle, olaylara tarafsız bir şekilde bakabiliyor ve duygusal tepkilerden uzak bir perspektifle düşünebiliyorsun.', 'nötr'),
    ('Beklenmedik bir tehlike karşısında, içinde bir korku dalgası yükseliyor ve içsel sıkıntılarla mücadele etmek zorunda kalıyorsun.', 'korkmuş'),
    ('Arkadaşımın bu davranışları karşısında çok rahatsız oldum. Ancak içimdeki bu tiksinme duygusuyla baş etmeye çalıştım.', 'tiksinmiş'),
    ('Gördüğüm haksızlık karşısında içimde bir öfke yükseliyor, sanki içimde bir volkan patlamaya hazır gibi. Adaletsizliğe, hukusuzluğa ve haksızlığa karşı içimdeki ateşle mücadele etmek gerçekten zorlayıcı olabiliyor.', 'öfkeli'),
    ('Bir vedanın ardından hissedilen derin üzüntü, gözlerde beliren yaşlarla birlikte yüreği sarıyordu. O anki hüzün, anıların ve geçmişin iç içe geçtiği bir duygusal yoğunluktu.', 'üzgün'),
    ('Bir şelalenin yanında oturduğumda, suyun akışını izlemek huzur dolu bir deneyim oluyor. Sanki zaman duruyor, her şeyin yerli yerinde olduğunu hissediyorum ve içsel bir dinginlik sarıyor ruhumu.', 'huzurlu'),
    ('Bir karar vermem gerektiğinde, içimdeki farklı duygular birbirleriyle yarışıyor. Bir yandan üzgünüm, bir yandan endişeliyim ve biraz da korkmuş hissediyorum. Karar vermek gerçekten zor olabiliyor.', 'duygu durumu karışık'),
    ('Elinden tuttuğunda, kalbin hızla çarpmaya başlıyor ve içindeki coşkuyla birlikte adeta havalanıyorsun.', 'heyecanlı'),
    ('Yüzümde beliren geniş bir gülümsemeyle, etrafımdaki her şey daha da parlak, daha da renkli görünüyor. İçimdeki sevinç, her bir adımımı dans eder gibi hafifletiyor ve dünya bana kutlu bir yer gibi geliyor.', 'mutlu'),
    ('Hayvanlara şefkatle yaklaştığında, içindeki sevgi dolu yaklaşımın onun da sana olan sevgisini arttırdığını hissediyorsun.', 'sevgi dolu'),
    ('Bir sırrı öğrendiğinde, şaşkınlıkla karışık bir duygu yaşıyor ve o gerçeği sindirmeye çalışıyorsun, sanki yeni bir dünyaya adım atmış gibi oluyorsun.', 'şaşkın'),
    ('Bazen etrafında gelişen olaylar karşısında, duygusal bir reaksiyon göstermeden sadece gözlemci konumunda kalmalısın.', 'nötr'),
    ('Dışarıdan gelen gürültüyle irkildim.', 'korkmuş'),
    ('Yemeği tattığım an içinde sevmediğim bir şey olduğunu anladım ve midem bulandı.', 'tiksinmiş'),
    ('Gelecek planlarını yaparken, belirsizliklerin yarattığı ihtimaller beni endişelendiriyor.', 'kaygılı'),
    ('Arkadaşımın bana ve aileme karşı yaptığı bu saygısızlık hem beni incitti hem de kızdırdı.', 'öfkeli'),
    ('Birinin yardımına ihtiyaç duyulduğunda hissedilen çaresizlik, yardım edememenin getirdiği acizlikle doluydu. O anki çaresizlik, birinin zor anında destek olamamanın yarattığı içsel bir boşluğu ifade ediyordu.', 'üzgün'),
    ('Bir sürprizle karşılaştığında, içindeki heyecanı gizlemeye çalışarak yüzünde beliren geniş bir gülümsemeyle o anın tadını çıkarıyorsun.', 'heyecanlı'),
    ('Yarınki sunum için duyduğum kaygı giderek artıyor, beklentileri karşılayabilecek miyim?', 'kaygılı'),
    ('Hayatın beklenmedik sürprizleri karşısında şaşkına döndüm.', 'şaşkın'),
    ('Karşılaştığımız durumlar bazen negatif bazen pozitif bir tepki yaratabilir, herkes farklı şeylere farklı tepkiler gösterebilir.', 'duygu durumu karışık'),
    ('Yeni yerler görmek beni mutlu ediyor.', 'mutlu'),
    ('Ona her baktığımda yeniden aşık oluyorum.', 'sevgi dolu'),
    ('İçinde bulunduğumuz durum karşısında tarafsız kalmak, bazen en sağlıklı seçenek olabilir.', 'nötr'),
    ('Son zamanlarda birden aklıma bu hayatta yalnız yaşayıp yalnız öleceğim düşüncesi geliyor ve bu düşünce beni korkutuyor.', 'korkmuş'),
    ('Bir kitabı okurken çayımı yudumlayıp yağmuru camdan izlemek, içimi huzurla dolduruyor.', 'huzurlu'),
    ('Annemle iş yaparken o işi onun istediği gibi yapmadığımda bana hep bağırıyor.', 'öfkeli'),
    ('Herkes, körü körüne emrine girdiği bu adama tiksinerek bakıyor.', 'tiksinmiş'),
    ('Aldığım haber karşısında sevinçten haykırdım.', 'mutlu'),
    ('Yeni bir spor dalı denemek istedim, ancak ya beceremezsem düşüncesi yüzünden cesaret edemedim..', 'kaygılı'),
    ('Arkadaşımın dediğine göre sevgilim evlenme teklifi edecekmiş. Heyecandan elim ayağıma dolaştı.', 'heyecanlı'),
    ('Beni orada sıcak bir yuva, huzurlu konuklar, mutlu bir kadın bekliyor.', 'huzurlu'),
    ('Düşünceleri dağılmış, karışmış, ne yapacağını bilemez duruma gelmiş.', 'şaşkın'),
    ('Birinden yana olmayan veya bir düşünceye, bir isteğe katılmayan, onu desteklemeyen, yan tutmayan; yansız, bitaraf, nötr biri o.', 'nötr'),
    ('Tuhaf şey! Hakikaten karışık bir kadın.', 'duygu durumu karışık'),
    ('O etrafta sürekli mahzun bir halde gezer..', 'üzgün'),
    ('Gerçek veya beklenen bir tehlike ile yoğun bir korku hissediyorum.', 'korkmuş'),
    ('Bu meydan okuyan öfkeli bekleyiş karşısında sustum.', 'öfkeli'),
    ('Bu ev niçin ona, tiksinç kuytularda düzensiz solumalar çağrıştırır?', 'tiksinmiş'),
    ('İlk kez denediğim oyun beni heyecanlandırdı.', 'heyecanlı'),
    ('Mutlu oldum.', 'mutlu'),
    ('Yanlış anlaşılmak can sıkıcı olabilir.', 'üzgün'),
    ('Aşkım beni sevgi dolu kucaklarla sardı.', 'sevgi dolu'),
    ('Ne oldu, iyi misin?', 'kaygılı'),
    ('Durum karışık, hem sevinçli hem de endişeli hissediyorum.', 'duygu durumu karışık'),
    ('Ondan nefret ediyorum.', 'öfkeli'),
    ('Beklenmedik haberler şaşırtıcı olabilir.', 'şaşkın'),
    ('Karanlık ve sessiz yerler korkutucu olabilir.', 'korkmuş'),
    ('Duygularımı ifade etmekte genellikle dengeliyimdir.', 'nötr'),
    ('Ona bakmak, dokunmak, kokusunu hissetmek çok rahatlatıcı.', 'huzurlu'),
    ('Sigara içen insanlardan iğreniyorum.', 'tiksinmiş'),
    ('Yaşlı amca otobüse binerken az kalsı düşüyordu. Onun için çok endişelendim.', 'kaygılı'),
    ('Genellikle nötr bir ruh halindeyim.', 'nötr'),
    ('Yakın arkadaşımın başarısı beni içtenlikle mutlu etti, onun başarısını görmek gurur duygusuyla dolmama sebep oldu.', 'mutlu'),
    ('Hediyesini açmak için sabırsızlanıyordu.', 'heyecanlı'),
    ('Birinin yardımına ihtiyaç duyduğumu hissetmek, hem yardım alma isteğiyle hem de gurur kırıklığıyla içimi doldurdu.', 'duygu durumu karışık'),
    ('Bana aşk dolu gözlerle baktığında içim kıpır kıpır oluyor.', 'sevgi dolu'),
    ('Uyumadan önce klasik müzik dinlemek, güzel bir uyku çekmemi sağlıyor.', 'huzurlu'),
    ('Arkadaşıın bana yaptığı şaka karşısında nutkum tutuldu.', 'şaşkın'),
    ('Şimdilerde zor zamanlardan geçiyorum. Çünkü yapmadığım bir şey için suçlandım.', 'üzgün'),
    ('Babam arkama aniden yaklaşınca yerimden zıpladım.', 'korkmuş'),
    ('Küçümsenmekten nefret ediyorum.', 'öfkeli'),
    ('Kan gibi uyarıcılar görmek veya koklamak bazı insanlarda tiksinme duygusu yaratabilir. ', 'tiksinmiş'),
    ('Geçen hafta sonu, köpeğim kaybolduğunda içimde büyük bir endişe oluştu. Onu bulana kadar sürekli kaygılıydım.', 'kaygılı'),
    ('Yoğun bir günün ardından, hiçbir duygusal tepki vermeden sadece sessizce odamda oturmak istedim. Genellikle nötr bir ruh halindeydim ve herhangi bir duyguyu dışa vurmaktan kaçınıyordum.', 'nötr'),
    ('En yakın arkadaşımın başarılı bir proje sonucunda ödül kazanması beni içtenlikle mutlu etti. Onun başarısı, gurur duygusuyla dolmama sebep oldu.', 'mutlu'),
    ('Yakın bir arkadaşımın doğum günü için aldığı hediyeyi açmak için sabırsızlanıyordu, heyecanı yüzünden okunuyordu.', 'heyecanlı'),
    ('Birinin yardımına ihtiyaç duyduğumu hissetmek, hem yardım alma isteğiyle hem de gurur kırıklığıyla içimi doldurdu.', 'duygu durumu karışık'),
    ('Sevdiğim insan bana aşk dolu gözlerle baktığında, içim kıpır kıpır oluyor.', 'sevgi dolu'),
    ('Ağaçların gölgeleri altında uzanmak ve sessiz bir göl kenarında kitap okumak, benim için huzurlu bir an yaratır. Doğanın sessizliği ve hafif rüzgarın esintisi, içimi huzurla doldurur.', 'huzurlu'),
    ('Arkadaşımın yaptığı şaka karşısında şaşkına döndüm, adeta nutkum tutuldu.', 'şaşkın'),
    ('Son zamanlarda zor bir dönemden geçiyorum. Yapmadığım bir şey için suçlandığım için oldukça üzgünüm..', 'üzgün'),
    ('Gece yarısı ani bir gürültüyle uyandığımda, kalbim hızla atmaya başladı ve etrafıma bakarken korkmuş bir şekilde titremeye başladım. O an, içimde belirsiz bir tehlikenin varlığıyla dolu bir korku hissettim.', 'korkmuş'),
    ('Her ne kadar acelem olsada trafik yüzünden geç kaldım ve bu yüzden bir güzel fırça yedim.', 'öfkeli'),
    ('Bugün benim için çok zor bir gün oldu.', 'üzgün'),
    ('İnsanların öksürmelerinden sonra o elleriyle otobüsün direklerini tutmaları çok iğrneç.', 'tiksinmiş'),
    ('Bir şeyi kaybettiğimde, içimde tarifsiz bir hüzün oluşuyor. Kaybetme duygusu içimi karartıyor.', 'üzgün'),
    ('Gece geç saatlerde yalnız kaldığımda içimde bir korku oluşuyor. Korku, etrafın sessizliğiyle birleşince daha da belirginleşiyor.', 'korkmuş'),
    ('Birisi bana yapıcı eleştirilerde bulunduğunda, hem minnettarlık hem de utanç hissediyorum. Öğrenmek için minnet duyarken kusurlarımı fark etmek utanç verici.', 'duygu durumu karışık'),
    ('Sıkıcı bir günün ardından güzel bir film izlemek, ruhumu pozitif bir enerjiyle doldurdu ve içimi mutluluk kapladı.', 'mutlu'),
    ('Sinirden küplere bindim.', 'öfkeli'),
    ("Evcil hayvanımın beni karşılamasıyla içim sevgi dolu oldu, onun sevgisini hissetmek harikaydı.", "sevgi dolu"),
    ("Heyecanlı bir günün ardından sessiz bir akşamda kitap okumak, içimi huzurla dolduruyor.", "huzurlu"),
    ("Beklenmedik bir haberle şaşkına döndüm, haber öyle şaşırtıcıydı ki cevap veremedim.", "şaşkın"),
    ("Yeni bir şey öğrenme isteğiyle dolup taşarken, içimde büyük bir heyecan oluşuyor.", "heyecanlı"),
    ("Bugün sakin ve dengeli bir gün geçirdim, içim oldukça nötrdü.", "nötr"),
    ("Gelecek planları hakkında belirsizlik hissetmek, içimde bir kaygı oluşturdu.", "kaygılı"),
    ("Belirli bir görüntü karşısında içimde bir tiksinme duygusu belirdi.", "tiksinmiş"),
    ("Sevgilimle yıldönümümüzde romantik bir akşam geçirdik. Onun gülümsemesiyle içim sevgi dolu oldu.", "sevgi dolu"),
    ("Birlikte ailece yapılan tatilde, içim mutlulukla doldu. Hep beraber geçirilen vakit bizi çok mutlu etti.", "mutlu"),
    ("Yaklaşan tatil planımızı konuşurken, içimizde büyük bir heyecan oluştu. Yeni yerler görmek çok heyecan verici.", "heyecanlı"),
    ("Doğanın ortasında sessiz bir piknik yapmak, içimi huzurla dolduruyor. Kuş sesleri ve rüzgarın melodisi sakinleştirici.", "huzurlu"),
    ("Beklenmedik bir anda karşıma çıkan eski bir arkadaşım, beni şaşkına çevirdi. O anki şaşkınlığımı gizleyemedim.", "şaşkın"),
    ("Bazı günler, içimde belirgin bir duygu olmadan geçer. Genellikle nötr bir ruh halinde olmak bazen iyidir.", "nötr"),
    ("Birisi için sevinirken, aynı zamanda onun başarısızlığından dolayı da üzüldüm. İçimde çelişkili duygular belirdi.", "duygu durumu karışık"),
    ("Sevdiğim birinin ani kaybı, içimi büyük bir üzüntüyle doldurdu. Onun eksikliği hissedilir derecede acı verici.", "üzgün"),
    ("Gece yürüyüşü yaparken beklenmedik bir ses duydum, içimde bir korku hissi oluştu. Ani tehlike belirtileri insanı ürkütüyor.", "korkmuş"),
    ("Haksızlığa uğradığımı düşündüğüm bir durumda, içimde büyük bir öfke oluştu. Adaletsizlik insanı öfkelendirebilir.", "öfkeli"),
    ("Gece yarısı ani bir gürültüyle uyandığımda, kalbim hızla atmaya başladı ve etrafıma bakarken korkmuş bir şekilde titremeye başladım. O an, içimde belirsiz bir tehlikenin varlığıyla dolu bir korku hissettim.", "kaygılı"),
    ("İnsanların öksürmelerinden sonra o elleriyle otobüsün direklerini tutmaları çok iğrenç.", "tiksinmiş"),
    ('Birisiyle yaşanan bir anlaşmazlık sonrasında özür dilemek ve barışmak, içimi rahatlama ve sevinçle doldurur.', 'mutlu'),
    ('Beklenmedik bir hediye almak, içimi şaşkınlık ve sevgiyle doldurur.', 'şaşkın'),
    ('Uzun bir seyahatin ardından evime dönmek, içimi huzur ve memnuniyetle doldurur.', 'huzurlu'),
    ('Bir spor müsabakasında takımımın zafer kazanması, içimi coşku ve gurur ile doldurur.', 'mutlu'),
    ('Bir doğa yürüyüşü sırasında etrafı incelemek, içimi merak ve huzur ile doldurur.', 'huzurlu'),
    ('Sevdiğim birinin başarılarına ortak olmak, içimi gurur ve sevinçle doldurur.', 'mutlu'),
    ('Bir sanat galerisinde farklı tarzlarda eserleri incelemek, içimi estetik bir keyif ve hayranlık ile doldurur.', 'mutlu'),
    ('Bir sevdikten alınan sürpriz bir telefon, içimi mutluluk ve şaşkınlıkla doldurur.', 'mutlu'),
    ('Bir zorlukla karşılaşıp onu aşmak, içimi başarı hissi ve güçlülük duygusu ile doldurur.', 'mutlu'),
    ('Birisiyle derin bir sohbet etmek ve duygusal bağ kurmak, içimi anlam ve sıcaklıkla doldurur.', 'mutlu'),
    ('Güzel bir manzara karşısında durmak, içimi hayranlık ve huzur ile doldurur.', 'huzurlu'),
    ('Eski bir arkadaşımla nostaljik anıları paylaşmak, içimi sevgi ve gülümseme ile doldurur.', 'mutlu'),
    ('Bir beceriyi geliştirmek için çaba harcamak ve başarılı olmak, içimi tatmin ve gurur ile doldurur.', 'mutlu'),
    ('Bir yaz gününde serin bir gölette yüzmek, içimi canlılık ve özgürlük hissiyle doldurur.', 'mutlu'),
    ('Sevdiğim bir kitabın devamını beklemek, içimi sabır ve heyecan ile doldurur.', 'heyecanlı'),
    ('Uzun zamandır görmediğim ailemle buluşmak, içimi sevgi ve mutlulukla doldurur.', 'sevgi dolu'),
    ('Evlat edindiğim sokak köpeğiyle oyun oynamak, içimi sevgi ve neşeyle doldurur.', 'sevgi dolu'),
    ('Bir yemekte kötü kokan bir yemeği zorla yemeye çalışmak, içimi tiksinçlik ve rahatsızlıkla doldurur.', 'tiksinmiş'),
    ('Uzun bir ilişkinin sona ermesi, içimi derin bir üzüntü ve kayıp hissiyle doldurur.', 'üzgün'),
    ('Önemli bir sınav öncesi duyduğum kaygı, içimi endişe ve gerginlikle doldurur.', 'kaygılı'),
    ('Birisiyle yaşanan anlaşmazlık, içimi öfke ve huzursuzlukla doldurur.', 'öfkeli'),
    ('Sevdiğim bir kitabın beklenmedik bir şekilde sona ermesi, içimi hayal kırıklığı ve boşlukla doldurur.', 'üzgün'),
    ('Bir iş görüşmesi için hazırlanırken duyduğum endişe, içimi kaygı ve belirsizlikle doldurur.', 'kaygılı'),
    ('Kötü bir haberle karşılaşmak, içimi üzüntü ve çaresizlikle doldurur.', 'üzgün'),
    ('Birisinin haksızlığa uğraması karşısında duyduğum öfke, içimi adaletsizlik ve sinirle doldurur.', 'öfkeli'),
    ('Bir karar verme sürecindeki belirsizlik, içimi kaygı ve endişeyle doldurur.', 'kaygılı'),
    ('Uzun süreli bir ilişkinin ardından duyulan boşluk, içimi üzüntü ve yalnızlıkla doldurur.', 'üzgün'),
    ('Trafikte sıkışıp kalmak ve geç kalma riski, içimi öfke ve stresle doldurur.', 'öfkeli'),
    ('Bir topluluk önünde konuşma yapmak için sahneye çıkmadan önce duyduğum kaygı, içimi endişe ve gerginlikle doldurur.', 'kaygılı'),
    ('Sevdiğim birinin sağlık sorunuyla karşılaşması, içimi üzüntü ve endişeyle doldurur.', 'üzgün'),
    ('Birisinin yanlış anlaşılması sonucu yaşanan anlaşmazlık, içimi öfke ve hayal kırıklığıyla doldurur.', 'öfkeli'),
    ('Evdeki sıcak bir kucaklama, içimi sevgi dolu bir sıcaklıkla doldurdu.', 'sevgi dolu'),
    ('Sevdiğim bir şarkının melodisi, içimi mutluluk ve huzur ile doldurur.', 'mutlu'),
    ('Bir macera filmi izlerken heyecanın doruklarına çıkmak, içimi heyecan ve enerjiyle doldurur.', 'heyecanlı'),
    ('Bir piknikte doğanın sessizliğini hissetmek, içimi huzur ve dinginlikle doldurur.', 'huzurlu'),
    ('Arkadaşlarımın hazırladığı sürpriz doğum günü partisiyle adeta şaşkına döndüm.', 'şaşkın'),
    ('Günün monotonluğu içinde, bir kitabı okurken hissettiğim duygu nötrdü.', 'nötr'),
    ('Duygusal karmaşa içindeki bir ilişkinin içinde bulunmak, içimi duygusal bir karışıklıkla doldurur.', 'duygu durumu karışık'),
    ('Bir dostun acılı hikayesini dinlerken, içimi derin bir üzüntü ve empati kaplar.', 'üzgün'),
    ('Gece yürüyüşü sırasında karanlıkta tuhaf sesler duymak, içimi korku ve endişeyle doldurur.', 'korkmuş'),
    ('Bir haksızlık karşısında adaletsizliği hissetmek, içimi öfke ve hayal kırıklığıyla doldurur.', 'öfkeli'),
    ('Yarın yapmam gereken sunum için kaygılıyım, acaba başarılı olabilecek miyim?', 'kaygılı'),
    ('Tiksinmiş bir şekilde o yemeği yedim.', 'tiksinmiş'),
    ('Bir korku filmi izlerken aniden kapının çalması, içimi korku ve gerilimle doldurur.', 'korkmuş'),
    ('Yolda kayarak düşmem sonucu aldığım yara, içimi hem acı hem de sinirle doldurur.', 'öfkeli'),
    ('İlk kez denediğim bir spor dalında başarısız olmak, içimi hayal kırıklığı ve utançla doldurur.', 'üzgün'),
    ('Bir konserde sevilen sanatçının şarkısını canlı dinlemek, içimi heyecan ve mutlulukla doldurur.', 'heyecanlı'),
    ('Bir şaka sonrasında odadaki herkesin gülüşü, içimi neşe ve mutlulukla doldurur.', 'mutlu'),
    ('Önemli bir sınavdan önce hissettiğim gerginlik, içimi kaygı ve stresle doldurur.', 'kaygılı'),
    ('Birine anlatılan dokunaklı bir hikaye, içimi duygusal bir karışıklıkla doldurur.', 'duygu durumu karışık'),
    ('Birisiyle yaşanan anlaşmazlık sonrasında barışmak, içimi huzur ve mutlulukla doldurur.', 'mutlu'),
    ('Kötü bir haberle karşılaşmak sonrasında hissettiğim tiksinçlik, içimi rahatsızlıkla doldurur.', 'tiksinmiş'),
    ('Birine yardım etmek ve minnettar bir tebessüm almak, içimi sevgi dolu bir mutlulukla doldurur.', 'sevgi dolu'),
    ('Bir kaza sonrasında hissettiğim korku, içimi titreme ve endişeyle doldurur.', 'korkmuş'),
    ('Uzun bir günün ardından sıcak bir banyo yapmak, içimi rahatlama ve huzur ile doldurur.', 'huzurlu'),
    ('Sevilen birini beklerken hissettiğim heyecan, içimi enerji ve mutlulukla doldurur.', 'heyecanlı'),
    ('Gece yatağa giderken içsel bir sükunet hissi, içimi huzurla doldurur.', 'huzurlu'),
    ('Bir projede başarılı olmanın getirdiği gurur, içimi memnuniyet ve başarıyla doldurur.', 'mutlu'),
    ('Birinin haksızlığa uğradığını görmek, içimi öfke ve adaletsizlikle doldurur.', 'öfkeli'),
    ('Sevilen bir kitabın bitmesi sonrasında hissettiğim boşluk, içimi hüzün ve melankoliyle doldurur.', 'üzgün'),
    ('Bir hedefe ulaşmanın getirdiği başarı hissi, içimi gurur ve sevinçle doldurur.', 'mutlu'),
    ('Birini kaybetmenin acısı, içimi derin bir üzüntü ve boşlukla doldurur.', 'üzgün'),
    ('Bir performans sonrasında alınan olumlu geri bildirim, içimi gurur ve mutlulukla doldurur.', 'mutlu'),
    ('Birisi tarafından takdir edilmek, içimi onay ve sevinçle doldurur.', 'mutlu'),
    ('Beklenmedik bir jestle sevildiğimi hissetmek, içimi sevgi ve mutlulukla doldurur.', 'sevgi dolu'),
    ('Zor bir karar vermek sonrasında hissettiğim belirsizlik, içimi kaygı ve endişeyle doldurur.', 'kaygılı'),
    ('Bir anı fotoğrafını gördüğümde hissettiğim nostalji, içimi duygusal bir karışıklıkla doldurur.', 'duygu durumu karışık'),
    ('Birine yalan söylenmesi karşısında duyduğum öfke, içimi sinir ve hayal kırıklığıyla doldurur.', 'öfkeli'),
    ('Birisi tarafından anlaşılmak, içimi huzur ve bağlılıkla doldurur.', 'mutlu'),
    ('Bir hedefe odaklanmak ve ona ulaşmak için harcanan çaba sonrasında hissettiğim memnuniyet, içimi gurur ve mutlulukla doldurur.', 'mutlu'),
    ('Birisi tarafından kucaklanmak, içimi sıcaklık ve sevgiyle doldurur.', 'sevgi dolu'),
    ('Uzun süreli bir dostluk ilişkisinin getirdiği güven, içimi huzur ve samimiyetle doldurur.', 'huzurlu'),
    ('Bir başarı hikayesini dinlemek ve o başarıya ortak olmak, içimi gurur ve mutlulukla doldurur.', 'mutlu'),
    ('Birisi tarafından takdir edilmek ve övgü almak, içimi memnuniyet ve sevinçle doldurur.', 'mutlu'),
    ('Doğanın güzelliklerini görmek, içimi hayranlık ve huzur ile doldurur.', 'huzurlu'),
    ('Bir arkadaşın sana olan güvenini hissetmek, içimi sevgi ve bağlılıkla doldurur.', 'sevgi dolu'),
    ('Bir tatil gününde keyifli bir kitap okumak, içimi huzur ve mutlulukla doldurur.', 'huzurlu'),
    ('Bir konsere gitmek ve sevdiğin sanatçıyı canlı dinlemek, içimi heyecan ve mutlulukla doldurur.', 'heyecanlı'),
    ('Birisi tarafından özel hissettirilmek ve düşünüldüğünü bilmek, içimi sevgi dolu bir mutlulukla doldurur.', 'sevgi dolu'),
    ('Bir engeli aşmak ve başarıya ulaşmak, içimi gurur ve mutlulukla doldurur.', 'mutlu'),
    ('Uzun bir günün ardından sevdiklerinle güzel bir sohbet etmek, içimi huzur ve mutlulukla doldurur.', 'huzurlu'),
    ('Birisi tarafından güzel bir kompliman almak, içimi memnuniyet ve sevinçle doldurur.', 'mutlu'),
    ('Birisi için endişelenmek ve sonra onların güvende olduğunu bilmek, içimi rahatlama ve sevgiyle doldurur.', 'sevgi dolu'),
    ('Bir şeyi başarıyla tamamlamak ve olumlu geri bildirim almak, içimi gurur ve mutlulukla doldurur.', 'mutlu'),
    ('Uzun bir süre sonra eski bir arkadaşımla karşılaşmak, içimi sevgi dolu bir nostaljiyle doldurur.', 'sevgi dolu'),
    ('Doğayla iç içe bir hafta sonu geçirmek, içimi huzur ve dinginlikle doldurur.', 'huzurlu'),
    ('Birisi tarafından güldürülmek, içimi neşe ve mutlulukla doldurur.', 'mutlu'),
    ('Birisinin yanında olduğunu bilmek, içimi güven ve sevgiyle doldurur.', 'sevgi dolu'),
    ('Uzun bir bekleyişin ardından sevdiğin birini görmek, içimi heyecan ve sevinçle doldurur.', 'heyecanlı'),
    ('Bir problemi çözmek ve başarıya ulaşmak, içimi gurur ve mutlulukla doldurur.', 'mutlu'),
    ('Bir doğa yürüyüşü sırasında kuş sesleri dinlemek, içimi huzur ve mutlulukla doldurur.', 'huzurlu'),
    ('Sevdiğin bir filmi tekrar izlemek, içimi nostalji ve mutlulukla doldurur.', 'mutlu'),
    ('Birisinin başarısını görmek ve onunla gurur duymak, içimi sevgi dolu bir mutlulukla doldurur.', 'sevgi dolu'),
    ('Uzun süreli bir bekleyişin ardından beklenen haberin gelmesi, içimi heyecan ve mutlulukla doldurur.', 'heyecanlı'),
    ('Birisi tarafından sarılmak, içimi sıcaklık ve sevgiyle doldurur.', 'sevgi dolu'),
    ('Bir konserde sevilen bir şarkıyı canlı dinlemek, içimi heyecan ve mutlulukla doldurur.', 'heyecanlı'),
    ('Uzun bir yolculuğun ardından evine dönmek, içimi huzur ve mutlulukla doldurur.', 'huzurlu'),
    ('Birisi tarafından anlaşılmak ve dinlenmek, içimi güven ve sevgiyle doldurur.', 'sevgi dolu'),
    ('Birisi için sürpriz bir doğum günü partisi düzenlemek, içimi mutluluk ve sevinçle doldurur.', 'mutlu'),
    ('Sevdiğin birini güldürmek, içimi neşe ve mutlulukla doldurur.', 'mutlu'),
    ('Uzun bir günün ardından sıcak bir çay içmek, içimi huzur ve rahatlama ile doldurur.', 'huzurlu'),
    ('Birisi tarafından minnettarlık ifadesi almak, içimi sevgi dolu bir mutlulukla doldurur.', 'sevgi dolu'),
    ('Bir çocuğun masum gülüşü, içimi sevgi ve neşeyle doldurur.', 'sevgi dolu'),
    ('Birisi tarafından güzel bir tebessümle karşılanmak, içimi sevgi dolu bir mutlulukla doldurur.', 'sevgi dolu'),
    ('Bir doğa manzarasını resmetmek, içimi yaratıcılık ve huzur ile doldurur.', 'huzurlu'),
    ('Birisi için önemli bir günü hatırlamak ve kutlamak, içimi sevgi ve mutlulukla doldurur.', 'sevgi dolu'),
    ('Birisi tarafından özenle hazırlanmış bir yemek yemek, içimi lezzet ve mutlulukla doldurur.', 'mutlu'),
    ('Uzun bir süre sonra sevdiğin birini aramak ve güzel bir sohbet etmek, içimi sevgi dolu bir mutlulukla doldurur.', 'sevgi dolu'),
    ('Birisi tarafından cesaretlendirilmek ve destek görmek, içimi güven ve mutlulukla doldurur.', 'mutlu'),
    ('Bir doğa yürüyüşü sırasında temiz hava solumak, içimi huzur ve canlılıkla doldurur.', 'huzurlu'),
    ('Birisinin yanında olduğunu bilmek, içimi güven ve sevgiyle doldurur.', 'sevgi dolu'),
    ('Bir konserde sevilen bir şarkının çalması, içimi heyecan ve mutlulukla doldurur.', 'heyecanlı'),
    ('Bir karmaşık durumun ortasında kalmak, içimi duygusal bir karışıklıkla doldurur.', 'duygu durumu karışık'),
    ('Bir sevilenin ani kaybı, içimi derin bir üzüntü ve boşlukla doldurur.', 'üzgün'),
    ('Gecenin ortasında duyulan garip sesler, içimi korku ve endişeyle doldurur.', 'korkmuş'),
    ('Birisinin haksızlığa uğradığını görmek, içimi öfke ve adaletsizlikle doldurur.', 'öfkeli'),
    ('Gelecek hakkında belirsizliklerle dolu olmak, içimi kaygı ve endişeyle doldurur.', 'kaygılı'),
    ('Bir şeyi düşündükten sonra hissettiğim tiksinçlik, içimi rahatsızlıkla doldurur.', 'tiksinmiş'),
    ('Bir önemli karar verme sürecinde sıkışıp kalmak, içimi kararsızlık ve duygusal karmaşa ile doldurur.', 'duygu durumu karışık'),
    ('Uzun bir ilişkinin ardından yaşanan ayrılık, içimi derin bir üzüntü ve yalnızlıkla doldurur.', 'üzgün'),
    ('Bir gece vakti tuhaf bir ses duymak, içimi korku ve rahatsızlıkla doldurur.', 'korkmuş'),
    ('Birisinin haksızlığa uğraması karşısında duyduğum öfke, içimi adaletsizlik ve sinirle doldurur.', 'öfkeli'),
    ('Gelecekle ilgili belirsizliklerin getirdiği endişe, içimi kaygı ve stresle doldurur.', 'kaygılı'),
    ('Bir şeyi düşündükten sonra hissettiğim tiksinçlik, içimi rahatsızlıkla doldurur.', 'tiksinmiş'),
    ('Bir an önce alınması gereken önemli bir kararın baskısı, içimi duygusal bir karmaşa ile doldurur.', 'duygu durumu karışık'),
    ('Yakın bir arkadaşımdan kötü bir haber almak, içimi derin bir üzüntü ve endişeyle doldurur.', 'üzgün'),
    ('Evde yalnızken duyulan garip sesler, içimi korku ve tedirginlikle doldurur.', 'korkmuş'),
    ('Birisinin haksızlığa uğradığını görmek, içimi öfke ve adaletsizlikle doldurur.', 'öfkeli'),
    ('Bir iş görüşmesinden önce hissettiğim kaygı, içimi endişe ve belirsizlikle doldurur.', 'kaygılı'),
    ('Bir şeyi düşündükten sonra hissettiğim tiksinçlik, içimi rahatsızlıkla doldurur.', 'tiksinmiş'),
    ('Bir ilişkide yaşanan karmaşık duygusal durumlar, içimi duygu durumu karışık bir huzursuzlukla doldurur.', 'duygu durumu karışık'),
    ('Bir yakınını kaybetmenin acısı, içimi derin bir üzüntü ve boşlukla doldurur.', 'üzgün'),
    ('Bir karşılaşma sırasında hissedilen yoğun korku, içimi endişe ve titremeyle doldurur.', 'korkmuş'),
    ('Bir haksızlığa uğramış birine yardım etme arzusu, içimi öfke ve adalet duygularıyla doldurur.', 'öfkeli'),
    ('Belirsiz bir geleceğin getirdiği kaygı, içimi belirsizlik ve gerginlikle doldurur.', 'kaygılı'),
    ('Bir şeyi düşündükten sonra hissettiğim tiksinçlik, içimi rahatsızlıkla doldurur.', 'tiksinmiş'),
    ('Bir an önce alınması gereken önemli bir kararın baskısı, içimi duygusal bir karmaşa ile doldurur.', 'duygu durumu karışık'),
    ('Yakın bir arkadaşımdan kötü bir haber almak, içimi derin bir üzüntü ve endişeyle doldurur.', 'üzgün'),
    ('Evde yalnızken duyulan garip sesler, içimi korku ve tedirginlikle doldurur.', 'korkmuş'),
    ('Birisinin haksızlığa uğradığını görmek, içimi öfke ve adaletsizlikle doldurur.', 'öfkeli'),
    ('Bir iş görüşmesinden önce hissettiğim kaygı, içimi endişe ve belirsizlikle doldurur.', 'kaygılı'),
    ('Bir şeyi düşündükten sonra hissettiğim tiksinçlik, içimi rahatsızlıkla doldurur.', 'tiksinmiş'),
    ('Bir ilişkide yaşanan karmaşık duygusal durumlar, içimi duygu durumu karışık bir huzursuzlukla doldurur.', 'duygu durumu karışık'),
    ('Bir yakınını kaybetmenin acısı, içimi derin bir üzüntü ve boşlukla doldurur.', 'üzgün'),
    ('Bir karşılaşma sırasında hissedilen yoğun korku, içimi endişe ve titremeyle doldurur.', 'korkmuş'),
    ('Bir haksızlığa uğramış birine yardım etme arzusu, içimi öfke ve adalet duygularıyla doldurur.', 'öfkeli'),
    ('Belirsiz bir geleceğin getirdiği kaygı, içimi belirsizlik ve gerginlikle doldurur.', 'kaygılı'),
    ('Bir şeyi düşündükten sonra hissettiğim tiksinçlik, içimi rahatsızlıkla doldurur.', 'tiksinmiş'),
    ('Bir an önce alınması gereken önemli bir kararın baskısı, içimi duygusal bir karmaşa ile doldurur.', 'duygu durumu karışık'),
    ('Yakın bir arkadaşımdan kötü bir haber almak, içimi derin bir üzüntü ve endişeyle doldurur.', 'üzgün'),
    ('Evde yalnızken duyulan garip sesler, içimi korku ve tedirginlikle doldurur.', 'korkmuş'),
    ('Birisinin haksızlığa uğradığını görmek, içimi öfke ve adaletsizlikle doldurur.', 'öfkeli'),
    ('Bir iş görüşmesinden önce hissettiğim kaygı, içimi endişe ve belirsizlikle doldurur.', 'kaygılı'),
    ('Bir şeyi düşündükten sonra hissettiğim tiksinçlik, içimi rahatsızlıkla doldurur.', 'tiksinmiş'),
    ('Bir ilişkide yaşanan karmaşık duygusal durumlar, içimi duygu durumu karışık bir huzursuzlukla doldurur.', 'duygu durumu karışık'),
    ('Bir yakınını kaybetmenin acısı, içimi derin bir üzüntü ve boşlukla doldurur.', 'üzgün'),
    ('Bir karşılaşma sırasında hissedilen yoğun korku, içimi endişe ve titremeyle doldurur.', 'korkmuş'),
    ('Bir haksızlığa uğramış birine yardım etme arzusu, içimi öfke ve adalet duygularıyla doldurur.', 'öfkeli'),
    ('Belirsiz bir geleceğin getirdiği kaygı, içimi belirsizlik ve gerginlikle doldurur.', 'kaygılı'),
    ('Bir şeyi düşündükten sonra hissettiğim tiksinçlik, içimi rahatsızlıkla doldurur.', 'tiksinmiş'),
    ('Bir an önce alınması gereken önemli bir kararın baskısı, içimi duygusal bir karmaşa ile doldurur.', 'duygu durumu karışık'),
    ('Yakın bir arkadaşımdan kötü bir haber almak, içimi derin bir üzüntü ve endişeyle doldurur.', 'üzgün'),
    ('Evde yalnızken duyulan garip sesler, içimi korku ve tedirginlikle doldurur.', 'korkmuş'),
    ('Birisinin haksızlığa uğradığını görmek, içimi öfke ve adaletsizlikle doldurur.', 'öfkeli'),
    ('Bir iş görüşmesinden önce hissettiğim kaygı, içimi endişe ve belirsizlikle doldurur.', 'kaygılı'),
    ('Bir şeyi düşündükten sonra hissettiğim tiksinçlik, içimi rahatsızlıkla doldurur.', 'tiksinmiş'),
    ('Bir ilişkide yaşanan karmaşık duygusal durumlar, içimi duygu durumu karışık bir huzursuzlukla doldurur.', 'duygu durumu karışık'),
    ('Bir yakınını kaybetmenin acısı, içimi derin bir üzüntü ve boşlukla doldurur.', 'üzgün'),
    ('Bir karşılaşma sırasında hissedilen yoğun korku, içimi endişe ve titremeyle doldurur.', 'korkmuş'),
    ('Bir haksızlığa uğramış birine yardım etme arzusu, içimi öfke ve adalet duygularıyla doldurur.', 'öfkeli'),
    ('Belirsiz bir geleceğin getirdiği kaygı, içimi belirsizlik ve gerginlikle doldurur.', 'kaygılı'),
    ('Bir şeyi düşündükten sonra hissettiğim tiksinçlik, içimi rahatsızlıkla doldurur.', 'tiksinmiş'),
    ('Bir an önce alınması gereken önemli bir kararın baskısı, içimi duygusal bir karmaşa ile doldurur.', 'duygu durumu karışık'),
    ('Yakın bir arkadaşımdan kötü bir haber almak, içimi derin bir üzüntü ve endişeyle doldurur.', 'üzgün'),
    ('Evde yalnızken duyulan garip sesler, içimi korku ve tedirginlikle doldurur.', 'korkmuş'),
    ('Birisinin haksızlığa uğradığını görmek, içimi öfke ve adaletsizlikle doldurur.', 'öfkeli'),
    ('Bir iş görüşmesinden önce hissettiğim kaygı, içimi endişe ve belirsizlikle doldurur.', 'kaygılı'),
    ('Bir şeyi düşündükten sonra hissettiğim tiksinçlik, içimi rahatsızlıkla doldurur.', 'tiksinmiş'),
    ('Bugün hava çok kötü.', 'üzgün'),
    ('Herkese merhaba arkadaşlar Bugün hava çok güzel ama kendimi kötü hissediyorum', 'duygu durumu karışık'),
    ('Maalesef sınavım kötü geçti.', 'üzgün'),
    ('Maalesef bugün çok kötü bir gün.', 'üzgün'),
    ('Allah kahretsin!', 'üzgün'),
    ('oh be yaşasın!', 'mutlu')


]
